### ISSUE TITLE
Remove about us dialog box

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-droidgen#1719]
**Actual Behaviour**

The about us dialog box displays the same information as the Home.

**Expected Behaviour**

Now that we have the new home layout, the dialog box is of no use.

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/29

**Comment by iamareebjamal** [comment]
About Fragment is Home

**Comment by arp95** [comment]
@mahikaw any progress?

**Comment by mahikaw** [comment]
Sending a PR 👍
