### ISSUE TITLE
Back arrow is enabled for Google Play Variant in Tablet mode

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-droidgen#1720]
**Actual Behaviour**

The back arrow is shown in Tablet mode in Google Map variant in Maps Fragment

**Expected Behaviour**

The back arrow should be hidden 

**Screenshots of the issue**

![device-2017-06-17-205241](https://user-images.githubusercontent.com/3874064/27254110-2f8b23be-539f-11e7-93d1-2859bbdfe2dd.png)

**Would you like to work on the issue?**

@arp95 Please fix

**Comment by arp95** [comment]
working on it.

**Comment by arp95** [comment]
@iamareebjamal please assign this milestone.
