### ISSUE TITLE
Get livefeed from Twitter

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-droidgen#1724]
**Actual Behaviour**

There is currently only facebook feed. 

**Expected Behaviour**

The twitter social link could be used to get the live feed with the help from loklak.

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

[milestone 10](https://github.com/fossasia/open-event-android/milestone/33)

**Comment by iamareebjamal** [comment]
We should focus on #1680 for now please. A lot of work is needed to finalize this. Besides, not even #1654 is complete, why assign a new issue till there are high priority issues open?

**Comment by rohanagarwal94** [comment]
@iamareebjamal got it. Will reopen it then after the issues are solved.

**Comment by rohanagarwal94** [comment]
@iamareebjamal I think its okay to open this now. Will use loklak API to fetch feed for a specific hashtag.

**Comment by iamareebjamal** [comment]
Sure

**Comment by mahikaw** [comment]
@rohanagarwal94 are you working on it?

**Comment by rohanagarwal94** [comment]
@mahikaw oh yes. Will open a WIP PR today after I complete my first iteration of work.

**Comment by codedsun** [comment]
@iamareebjamal I want to work on this issue.

**Comment by iamareebjamal** [comment]
Please go ahead

**Comment by dr0pdb** [comment]
@iamareebjamal Since there hasn't been any progress on this issue from @codedsun , I would like to claim this.

**Comment by iamareebjamal** [comment]
Please go ahead
