### ISSUE TITLE
Implement marker clustering in map fragment

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-droidgen#1730]
**Actual Behaviour**

Due to large number of microlocations in events like [Mozilla All Hands](https://github.com/fossasia/open-event/blob/master/sample/MozillaAllHands17/microlocations) , the map UI gets clumsy.

**Expected Behaviour**

The markers should cluster itself to on zoom out and decluster on zoom in.

**Screenshots of the issue**

Something like this.

![mapactivity2](https://user-images.githubusercontent.com/13241256/27418949-caa5c5f8-573b-11e7-9480-1dc596179948.png)

**Would you like to work on the issue?**

Yes after the priority issues are solved.

**Target Milestone to solve the issue**

[milestone 7](https://github.com/fossasia/open-event-android/milestones/30)

**Comment by rohanagarwal94** [comment]
@iamareebjamal please discuss this. This could be valuable IMO.

**Comment by iamareebjamal** [comment]
Yes please go ahead

**Comment by rohanagarwal94** [comment]
@iamareebjamal please set milestone.
