### ISSUE TITLE
Displaying Title in HomePage from event.json file

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-droidgen#1734]
**Actual Behaviour**

Currently the app just shows the Fossasia title in the homepage.

**Expected Behaviour**

Displaying the title of the event from the event.json file.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/31

**Comment by rohanagarwal94** [comment]
@arp95 please add the screenshot. 

![screenshot_2017-06-25-20-21-44-260_org fossasia openevent f8facebookdeveloperconference2017](https://user-images.githubusercontent.com/13241256/27517116-492c0afe-59e4-11e7-9670-4520bd6be55d.png)
