### ISSUE TITLE
Implement caching in the livefeed

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-droidgen#1735]
**Actual Behaviour**

The livefeed currently works only online.

**Expected Behaviour**

The previously fetched feed should be displayed in case the user is offline.

**Steps to reproduce it**

1. Open livefeed item from the nav drawer without the internet

**Screenshots of the issue**

![screenshot_2017-06-25-20-27-27-793_org fossasia openevent](https://user-images.githubusercontent.com/13241256/27517159-40d495b4-59e5-11e7-9ded-7ba000c6a030.png)

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

[milestone 8](https://github.com/fossasia/open-event-android/milestones/31)

**Comment by arp95** [comment]
@rohanagarwal94 
please go ahead!

**Comment by rohanagarwal94** [comment]
@iamareebjamal please add milestone
