### ISSUE TITLE
Add progress bar to the livefeed

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-droidgen#1736]
**Actual Behaviour**

Currently empty screen is shown before the feed loads into the view.

**Expected Behaviour**

There should be a progress bar while the feed loads. @iamareebjamal @arp95 @Shailesh351 @shreyasnbhat @mahikaw should the circular progress bar be used or the normal progress bar shown at the start of the app?

**Screenshots of the issue**

![screenshot_2017-06-25-20-27-27-793_org fossasia openevent](https://user-images.githubusercontent.com/13241256/27517199-3da4370e-59e6-11e7-9829-981b3a98a364.png)

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

[milestone 8](https://github.com/fossasia/open-event-android/milestones/31)

**Comment by arp95** [comment]
According to me its better to include the livefeed with the progress bar in the start when the download happens.

**Comment by rohanagarwal94** [comment]
@arp95 there is a problem with that. Since we are not storing the feed in realm, it is impossible that the view populates itself when the user clicks to see the feed.

**Comment by rohanagarwal94** [comment]
@iamareebjamal please suggest the appropriate UI and add the milestone.

**Comment by iamareebjamal** [comment]
We've been using the toolbar progress up until now. UI should be consistent IMO
