### ISSUE TITLE
Improvement of HomeFragment UI to improve Bookmarks Visibility

### ISSUE THREAD

**Issue by shreyasnbhat** [fossasia/open-event-droidgen#1741]
**Actual Behaviour**
As of now the bookmarks are arranged in a horizontal list of cards in the HomeFragment.

**Expected Behaviour**
What I intend to do is a UI refactor to use the DayScheduleViewHolder to showcase the bookmarks in a vertical list in the home screen similar to the Google I/O app.
@iamareebjamal @arp95 @mahikaw @Shailesh351 Suggestions? 

**Would you like to work on the issue?**
Yes

**Target Milestone to solve the issue**
https://github.com/fossasia/open-event-android/milestone/31

**Comment by arp95** [comment]
can you show some mockup @shreyasnbhat ?
also please dont hardcode the twitter icon, fb icon, youtube icon. i was about to open an issue for it. just check whether event.json has all these links and then make them visible.

**Comment by shreyasnbhat** [comment]
@arp95 If you check out the Google I/O 2017 App the homescreen. I was thinking on those lines.
And for the icons you talk about I didn't actually code the AboutFragment I just used the existing class. Will fix it soon.

**Comment by arp95** [comment]
@shreyasnbhat 
i was having a look yesterday. it has a homepage only for bookmarked sessions as i could see.
for details it had another icon having four tabs: travel, about etc.
what do you think, should we follow their approach to divide stuff or include all in one fragment?

**Comment by shreyasnbhat** [comment]
I think we should just edit the Bookmarks Fragment and make it like the Google I/O Home Screen. And leave the rest for now. We will have to think a bit how to improve the Home Screen UI.

**Comment by arp95** [comment]
umm then i would say use a vertical listing of them after the title.

**Comment by shreyasnbhat** [comment]
I would say that we do it datewise itself.Just like the Google I/O App.

**Comment by arp95** [comment]
yeah i meant vertical scrolling like the schedule page. this is what you mean right?

**Comment by Shailesh351** [comment]
In my opinion it will be good to display event and organisation info in About fragment because it will not be good to display event and organization info every time user opens app.

And for bookmarks we have already it in home fragment just it should be vertical.

**Comment by shreyasnbhat** [comment]
@Shailesh351  We wont be seeing organizer info everytime. We will be seeing it below the bookmarks.
And @Shailesh351 in the time I have spent using the app I have hardly even used the About feature. A user feels that it is to convey about the app and not about the event itself. So I feel that the current situation is fine.

**Comment by arp95** [comment]
i feel @Shailesh351 is right. because seeing event info everytime doesnt make sense.
rest is upon others what they think.

**Comment by shreyasnbhat** [comment]
@iamareebjamal Suggest? 
@Shailesh351 The About section in the navHeader is a bit misleading though. Most about sections of apps do not contain what the event is about but contain stuff like developer details and company information. Organizer Info could go into another fragment such as About Event but that would just clutter the navBar.

**Comment by arp95** [comment]
yeah we should create about fragment for the event info. 
home fragment is all about the user oriented stuff which right now is the bookmarks only.

**Comment by shreyasnbhat** [comment]
http://2017.fossasia.org/
Check this out. The first page always contains Information about the Event.
I guess we should wait to hear from others.

**Comment by shreyasnbhat** [comment]
@iamareebjamal Add a milestone to this too. I'll start working on the Bookmarks UI change as said above. If another fragment for the event is needed I'll do that in a separate issue.

**Comment by shreyasnbhat** [comment]
@iamareebjamal @arp95 @Shailesh351 
Please tell me how does this look.
![60ba24bd-b9b2-4290-b878-e3de3f938e4a](https://user-images.githubusercontent.com/19890557/27676689-8d4e01fc-5ccc-11e7-8ca6-d3104edd8988.jpg)
