### ISSUE TITLE
Improve About Event Homescreen UI

### ISSUE THREAD

**Issue by shreyasnbhat** [fossasia/open-event-droidgen#1753]
**Actual Behaviour**
Currently the UI is a bit overcrowded with small cards and bold titles.

**Expected Behaviour**
I feel that for the event location and venue we could have something like this.
![1287274cd934b6b2b1fbb79572f108ef--iphone-ui-ui-ux](https://user-images.githubusercontent.com/19890557/27733743-5fcf7aaa-5db5-11e7-85a3-e7bb2751baf6.jpg)
In a gist I would be removing the cards that have only single lines as their content and do something like the above. And I would be removing the cards itself keeping the layout cardless.

Other suggestions are welcome.
@arp95 @Shailesh351 @iamareebjamal @rohanagarwal94 

**Would you like to work on the issue?**
Yes

**Target Milestone to solve the issue**
@iamareebjamal  Please add https://github.com/fossasia/open-event-android/milestone/31 as the milestone.

**Comment by arp95** [comment]
This is also fine. 
I was also thinking we can divide the information in the form of tabs like in schedule page. So a home screen opens up having about tab displaying event info, bookmarks tab to display user oriented stuff, and more if this idea seems feasible.

**Comment by shreyasnbhat** [comment]
@arp95 We could have 2 tabs if we have more information which supports the event info. Like the Google I/O app has information about how to get to the venue ,helpline numbers etc. If we had our api server meeting these requirements we could have all this information displayed in  separate tabs for sure. But as the information for the event isn't much I don't think right now we should have tabs. But tab layout should be preferred is more information about the event is present. 
@iamareebjamal  @Shailesh351  What do you think?

**Comment by shreyasnbhat** [comment]
Current Iteration of the UI design.
@arp95 @Shailesh351 @iamareebjamal @rohanagarwal94 Please give your thoughts on this.
![6362aa08-afdb-4679-a070-da24a97980ca](https://user-images.githubusercontent.com/19890557/27751139-8a163fea-5df8-11e7-8064-d86d81bb5fc3.jpg)
![229bd481-2e3b-4ed5-ba10-c44b8ee8e41d](https://user-images.githubusercontent.com/19890557/27751140-8a958fca-5df8-11e7-8cb0-0f49d60b9a33.jpg)

**Comment by arp95** [comment]
Yeah you are right.
i thibk this ui looks great. Lets see what others think.

**Comment by Shailesh351** [comment]
UI Looks good :+1:

**Comment by shreyasnbhat** [comment]
@Shailesh351 @arp95 Has any one of you noticed that the `map_marker.xml` has a wierd padding below and to the right of it. Is it intended or not?

**Comment by arp95** [comment]
yeah i just saw that. we should remove that.

**Comment by shreyasnbhat** [comment]
@arp95 I'll remove that xml and add a drawable
I'll then send a pr for the same.
