### ISSUE TITLE
adding support for new attributes in Session model

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-droidgen#1756]
**Actual Behaviour**

Currently the old model doesnt support created-at, deleted-at, submitted-at and is-mail-sent attributes of new model.

**Expected Behaviour**

Adding support for them.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

@iamareebjamal please add it.
https://github.com/fossasia/open-event-android/milestone/31

**Comment by arp95** [comment]
@iamareebjamal 
just the Session file would change right?
You told changes will happen in Realm but i dont see any where in realm files individual attributes of session object being used? It looks like realm saves the session object if i am right?

**Comment by iamareebjamal** [comment]
Yes, but on pre-existing apps, the Realm Schema would be set and it'll crash on finding new attributes

**Comment by iamareebjamal** [comment]
You'll have to add fields like here https://realm.io/docs/java/latest/#migrations
