### ISSUE TITLE
App crash in the livefeed

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-droidgen#1758]
**Actual Behaviour**

The app is crashing in the live feed after the latest series of merges.

**Expected Behaviour**

The live feed should work fine.

**Steps to reproduce the issue**

1. Open the app.
2. The progress bar seems to be be stuck at 85%.
3. Minimise the app.
4. Open the live feed tab from the Nav Drawer.

**LogCat for the issue**

![screenshot from 2017-07-01 16-12-38](https://user-images.githubusercontent.com/13241256/27761425-38a1234c-5e79-11e7-9393-89e065e996f6.png)

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

[milestone 8](https://github.com/fossasia/open-event-android/milestones/31)

**Comment by Shailesh351** [comment]
@rohanagarwal94 Please provide steps to reproduce issue

**Comment by rohanagarwal94** [comment]
@shailesh351 updated.
