### ISSUE TITLE
Search icon color issue

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-droidgen#1762]
**Actual Behaviour**

Search icon color is changing to black after opening trackSessions activity when track font-color is black same for other track-font-color.

**Expected Behaviour**

Seach icon color shoud be managed properly to show appropriate color.

**Steps to reproduce it**

- Go to Tracks fragment
- Click on "AI & Machine Learning" track
- Press back button
- Now go to schedule fragment, search icon color is changed.
- Press back button, search icon color in home fragment also changes.

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

[Milestone 9](https://github.com/fossasia/open-event-android/milestone/32)

**Comment by arp95** [comment]
please go ahead.
