### ISSUE TITLE
Set appropriate placeholder for the live feed

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-droidgen#1764]
**Actual Behaviour**

The placeholder currently set looks absurd and out of context.

**Expected Behaviour**

The placeholder should look apt for the task.

**Screenshots of the issue**

![screenshot_2017-07-02-23-09-52-853_org fossasia openevent](https://user-images.githubusercontent.com/13241256/27772287-95c21a50-5f7c-11e7-97c9-2fddbe1f623c.png)

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

[milestone 9](https://github.com/fossasia/open-event-android/milestone/32)

**Comment by rohanagarwal94** [comment]
@iamareebjamal please set milestone.

**Comment by shreyasnbhat** [comment]
@rohanagarwal94 It would be nice if you added the comment box inside the card itself.

**Comment by rohanagarwal94** [comment]
@shreyasnbhat definitely an option. Lets see what others think about it. @iamareebjamal @arp95 @Shailesh351 views on the placeholder and comment box?
![screenshot_2017-07-03-20-22-35-275_org fossasia openevent](https://user-images.githubusercontent.com/13241256/27798201-01390fb2-602e-11e7-966c-101f170b8c0b.png)
