### ISSUE TITLE
Downloader progress bar issue

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-droidgen#1765]
**Actual Behaviour**

There is an absurd behaviour in the progress bar on a certain followed pattern. The download progress bar refuses to close too.

**Expected Behaviour**

The progress bar should work fine.

**Steps to reproduce it**

1.Open the app.
2.Turn the internet connection off.
3.Turn it on again.
4. The download progress bar starts.
5. After it completes, turn the internet off again.
6. Turn it back on.

**Screenshots of the issue**

![screenshot_2017-07-02-23-20-18-224_org fossasia openevent](https://user-images.githubusercontent.com/13241256/27772381-ac1da592-5f7e-11e7-82ea-6b6aedb75fc7.png)

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

[milestone 9](https://github.com/fossasia/open-event-android/milestone/32). @iamareebjamal please add milestone.

**Comment by arp95** [comment]
@rohanagarwal94 
are you working on this?

**Comment by rohanagarwal94** [comment]
Yeah I am. Its just that its difficult to debug this. The download events are getting subscribed again and again. Will take help if I am unsuccessful on this.

**Comment by rohanagarwal94** [comment]
@iamareebjamal @arp95 @shreyasnbhat @Shailesh351  need some help with this. As far as I debugged the issue, the problem is that the [onReceive](https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/java/org/fossasia/openevent/utils/NetworkUtils.java#L125) method is being called 4 times simultaneously. Hence 4 API requests by 2 different intent actions of the receiver are being made thereby causing the bug. Now I found a workaround to it - https://stackoverflow.com/a/8413512 but it seems not a good solution. Please suggest whether to use the work around or maybe any other solution which might work.

**Comment by iamareebjamal** [comment]
Either block API request if already in transit. Easiest and correct way to handle it
Or, cancel previous ones when a new one is made

**Comment by iamareebjamal** [comment]
Actually, the current interaction where network is checked via BroadcastReceiver is very convoluted, and besides that, app even sends ping to google to verify if connection is working. This creates complex problems and user needs to wait for whole round trip time before being able to do any action. I think we should only check by context is device is actually connected to internet at the time of action as retrofit already supports timeout.

@the-dagger What do you think?

**Comment by the-dagger** [comment]
>I think we should only check by context is device is actually connected to the internet at the time of action as retrofit already supports timeout.

@iamareebjamal Sounds good to me.

**Comment by rohanagarwal94** [comment]
@iamareebjamal the method is called 4 times when there is an active internet connection which is why the event bus results in [4 consecutive new download events](https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/java/org/fossasia/openevent/utils/NetworkUtils.java#L130).

**Comment by iamareebjamal** [comment]
@rohanagarwal94 Now as @the-dagger has given a go to it, you can use [haveNetworkConnectionObservable](https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/java/org/fossasia/openevent/utils/NetworkUtils.java#L34) instead

**Comment by rohanagarwal94** [comment]
:+1:
