### ISSUE TITLE
Adding session videos using video URL

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-droidgen#1771]
**Actual Behaviour**

Currently, If the video is not a youtube video, an external intent is passed which opens up the link on the browser app.

**Expected Behaviour**

A Web View should be used  instead so that a new app isn't opened and that the video can still play in the session details Activity.

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 
https://github.com/fossasia/open-event-android/milestone/32

------
@the-dagger @mariobehling  @niranjan94 @mananwason Shall I go ahead with this?

**Comment by iamareebjamal** [comment]
@mahikaw Please take a look at #1686 

Using VideoView will require you to load the video from the stream first and then show, which I think is beyond the scope of the app. Secondly, the video URL will not necessarily be a stream URL, so you'll have to parse the URL, fetch information about it and apply complex logic to provide a basic solution -> let the pre-existing apps handle the Video Feed by Intent System

**Comment by arp95** [comment]
please close this issue @mahikaw

**Comment by mahikaw** [comment]
@iamareebjamal @arp95 If the link is not a youtube link, it passes an intent to a browser. I think we should insert a `Web View` instead. I'll update the issue.

**Comment by rohanagarwal94** [comment]
I feel this could be of use https://developers.google.com/youtube/android/player/

**Comment by iamareebjamal** [comment]
If we use a web view, then user can not use other streaming apps he has installed like VLC or MX Player, we should not be substituting for browser IMO

@rohanagarwal94 I think this is beyond the scope of project to show YouTube videos

@the-dagger Please suggest

**Comment by mahikaw** [comment]
@iamareebjamal I think it still plays the video on the browser. Doesn't use apps like VLC or MX player, even when they are installed.

**Comment by rohanagarwal94** [comment]
@iamareebjamal as far as the size is concerned it wont be much affected if we use proguard. Its there on the website. Besides we could include videos about the event with this in the feed itself too.

**Comment by the-dagger** [comment]
@mahikaw @iamareebjamal The current implementation is totally fine, adding a webview for streaming media content makes no sense to me.
This is an event app, not a media browser app in any sense.

Closing this issue.
