### ISSUE TITLE
Addition Of Placeholder in Sponsors

### ISSUE THREAD

**Issue by shreyasnbhat** [fossasia/open-event-droidgen#1775]
**Actual Behaviour**
Doesn't Exist now.

**Expected Behaviour**
Should have a placeholder.

**Would you like to work on the issue?**
Yes

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/31

**Comment by shreyasnbhat** [comment]
@iamareebjamal @arp95  As of now if I add a placeholder the placeholder gets resized to the size of the actual image and cross fades between the 2 images. If I remove the fade effect it doesn't look great.

The placeholder resizing problem is a problem in the library supposedly. So what do you suggest I do?

**Comment by arp95** [comment]
you can provide the placeholder as the dimensions of the image view i guess. then if internet is present then the image would get loaded. use the resizing property of picasso so that we are taking into account of the sponsor which gets loaded.

**Comment by shreyasnbhat** [comment]
So you are saying I set the imageView background as the placeholder instead?

**Comment by arp95** [comment]
yes, so that when image loads it comes on top of the placeholder.

**Comment by the-dagger** [comment]
@shreyasnbhat @arp95 I think that we are focusing too much on the minute details right now.
There is really no need of starting a discussion on how a placeholder should appear on top of an imageView.
Just focus on getting it done and send a pull request with a gif, you'll get the suggestions over there.

If we continue to have such discussion about each and every topic then the pace of the project will be drastically reduced.

We also have to work on the app generator, which I can't see anyone really working on.
Do you realize that the open-event-android project is a combination of client + generator?

At the end of GSoC, you need to have a working client and generator along with APIs which allow anyone to build the app from command line.

I'm not sure if you'll be able to achieve this with the current state of redundant discussions.

**Comment by arp95** [comment]
yes @the-dagger you are right.
but right now i am working on the models of the app and getting them according to the new api.
can we divide the work @shreyasnbhat @Shailesh351 as @iamareebjamal is busy with the orga app?

**Comment by the-dagger** [comment]
@arp95 sure you are free to divide work among yourselves.
Just discuss this on the gitter channel and make sure that everyone is on the same page.

**Comment by shreyasnbhat** [comment]
@arp95 Sure!
@the-dagger Will do.
