### ISSUE TITLE
Build and push all the sample apps in apk branch after each commit

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-droidgen#1780]
The samples are listed at : https://github.com/fossasia/open-event
Modify the build script so that every apk is generated and committed after each push to the development branch.
You'll need to modify the BASE_URL according to each sample's raw json URL.

**Comment by shreyasnbhat** [comment]
I'll take this up.

**Comment by the-dagger** [comment]
@shreyasnbhat Please see #1676
