### ISSUE TITLE
Upcoming/ongoing sessions Trackwise feature

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-droidgen#1785]
**Actual Behaviour**

There is no way to find out the upcoming and ongoing sessions in a particular track other than manually searching for it. 

**Expected Behaviour**

There should be an option that displays the ongoing/upcoming sessions by auto scrolling to the ongoing/upcoming session, including a label on every session card.

**Screenshots of the issue**

I made some mock-ups

![device-2017-07-06-202347](https://user-images.githubusercontent.com/21010060/27959954-220cef26-6347-11e7-9fc0-faef50981f62.png)

![device-2017-07-06-202505](https://user-images.githubusercontent.com/21010060/27959597-be343352-6345-11e7-8ca0-1717169aea06.png)

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing 
the issue? 
https://github.com/fossasia/open-event-android/milestone/32

----

@the-dagger @mananwason @niranjan94 @mariobehling Shall I go ahead with this?

**Comment by shreyasnbhat** [comment]
@mahikaw Please make the UPCOMING text color coded.
UPCOMING - Green
ONGOING - Yellow
FINISHED  - Red

**Comment by mahikaw** [comment]
@shreyasnbhat I had given some thinking into it. I was thinking that coloured text won't look nice with different track colours.  For instance, "upcoming" green would be less highlighted if the track colour is also green. What is your say?

**Comment by iamareebjamal** [comment]
For more than 1 speaker, ONGOING will overlap

**Comment by mahikaw** [comment]
How do you mean @iamareebjamal? You mean the TextViews will overlap?

**Comment by iamareebjamal** [comment]
Yes

**Comment by mahikaw** [comment]
Um no. I checked that. In case of more than one speakers, it'll look something like this. I adjusted the dimensions of speaker textview.

![device-2017-07-08-013605](https://user-images.githubusercontent.com/21010060/27974972-ee9c11d0-637d-11e7-88c1-9b94892672b8.png)

Does this look okay?

**Comment by shreyasnbhat** [comment]
@mahikaw I am not saying that set the text green or red. You could add a border to the text view which could be red or green.

**Comment by mahikaw** [comment]
@shreyasnbhat That too is bound to interfere if the colour of track is green or red. But thanks for the suggestion, let's wait for others to review. :)

**Comment by mahikaw** [comment]
Shall I go ahead with this @mariobehling @the-dagger @niranjan94  @mananwason @iamareebjamal @shreyasnbhat @Shailesh351 @rohanagarwal94 @arp95 ?

**Comment by mananwason** [comment]
Go ahead @mahikaw.
