### ISSUE TITLE
Adding and modifying the status messages in generator.py

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-droidgen#1786]
**Actual Behaviour**

Modified and added status messages in generator.py file.

**Expected Behaviour**

Doing the required changes.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

-

**Target Milestone to solve the issue**

@iamareebjamal please add it.
https://github.com/fossasia/open-event-android/milestone/32

**Comment by niranjan94** [comment]
@arp95 it would be great if you could work on _actual_ issues. This is really not a proper issue ...

**Comment by arp95** [comment]
yes i know this was of less relevance, sorry will take care from next time onwards.
should i close this then?

**Comment by arp95** [comment]
@niranjan94 closing this then.
