### ISSUE TITLE
Null pointer exception while fetching start time from sessions

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-droidgen#1790]
**Actual Behaviour**

The downloader dialog is getting stuck at 85% due to a null pointer exception after a recent merge.

**Expected Behaviour**

The event should be downloaded fine.

**Steps to reproduce it**

1. Re download app after pulling changes.

**LogCat for the issue**

![screenshot from 2017-07-09 00-28-30](https://user-images.githubusercontent.com/13241256/27988373-f19b53e4-643d-11e7-83aa-77c57350734a.png)

@arp95 @iamareebjamal @Shailesh351 is this expected since I saw a commit from @arp95 making changes to Sessions.java.

**Comment by iamareebjamal** [comment]
@rohanagarwal94 This is expected as the app is using the attribute naming of next-gen API now.

**Comment by iamareebjamal** [comment]
The old API name was start_time and now it is starts-at and we don't need to support old API, so as soon as all the models get converted to JSONAPI format, we will change base URL to nextgen API and this won't happen

**Comment by rohanagarwal94** [comment]
@iamareebjamal got it. Closing this then.
