### ISSUE TITLE
Issue during downloading content after installing of App

### ISSUE THREAD

**Issue by S2606** [fossasia/open-event-droidgen#1794]
**Actual Behaviour**

regarding status of downloading event info, both downloaded as well as downloading is been displayed.

**Expected Behaviour**

Only downloaded status should be shown once its being downloaded.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/18497513/27993360-514bfe5e-64c7-11e7-8bb8-dc43c8fc9554.png)

**Would you like to work on the issue?**

No.

**Comment by rohanagarwal94** [comment]
@S2606 this is expected as the project is in the middle of API transition. Please close this for now.
