### ISSUE TITLE
Adding user feedback option in SessionDetailActivity

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-droidgen#1795]
**Actual Behaviour**

Currently there is no option for user to provide feedback for a session.

**Expected Behaviour**

Adding a feedback button which will allow the user to write feedback and then share this or privately share this with fossasia on twitter or fb instead of sending he redponse back to the server as we dont have functionality for this now.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/33

@niranjan94 @iamareebjamal @Shailesh351 @sheyasnbhat @rohanagarwal94 
what do you think of this?

**Comment by mahikaw** [comment]
@arp95 The server is moving to API implementation as of now after which, this functionality will be added in a proper way with integration from server.
Thus, in my view it will be better to close this issue for now as this is just a temporary solution. We could solve it in a proper way once the server is ready. :)
