### ISSUE TITLE
Adding additional properties to the email field in the generator.py

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-droidgen#1796]
**Actual Behaviour**

Right now the email field doesnt have two properties for it:

1. autofocus which lets the focus on email field once the page loads.
2. autocomplete which lets the browser predict the value once the user starts typing in.

**Expected Behaviour**

Doing the above changes.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

@iamareebjamal please add it.
https://github.com/fossasia/open-event-android/milestone/33

**Comment by niranjan94** [comment]
@arp95 like I pointed out yesterday ... It would be so much better if you could work on actual issues that benefit the project. How does browser autofocusing on the email field or changing `required` to `required="true"` (`required="true"` is not at all necessary btw) help the generator or the app in anyway significant ? 

Your contributions are already way too low. It's high time you start taking things more seriously.

**Comment by arp95** [comment]
ok @niranjan94.

**Comment by niranjan94** [comment]
@arp95 You really didn't have to close the PR/issue. Since you had already started. All I said was to work on more significant issues too.
