### ISSUE TITLE
Add choice for build variant at time of app generation

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-droidgen#1801]
**Actual Behaviour**

The app contains both google play variant and FOSS variant, but we only provide single variant to download after the generation.

**Expected Behaviour**

Add option to select which app to build and provide download to that app

**Would you like to work on the issue?**

No

**Comment by arp95** [comment]
working on it.

**Comment by arp95** [comment]
@iamareebjamal please assign me on this and add this to next milestone. Thanks!
