### ISSUE TITLE
Enhance the bookmark widget

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-droidgen#1816]
**Actual Behaviour**

1. The UI is not in sync with the bookmarks UI in app.
2. The bookmarks dont show more than one bookmarks in the widget.
3. No option to remove bookmark.

**Expected Behaviour**

The bookmark widget should be in total sync with app bookmark.

**Screenshots of the issue**

![screenshot_2017-07-13-20-14-38-047_com miui home](https://user-images.githubusercontent.com/13241256/28172868-6f453e34-680a-11e7-9d78-8c40a3e04672.png)

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

[milestone 10](https://github.com/fossasia/open-event-android/milestone/33)

**Comment by shreyasnbhat** [comment]
@rohanagarwal94 Also check if the bookmarks are getting updated. Once I saw  that the bookmarks weren't getting updated. It's a very random issue. Just check it out.

**Comment by shreyasnbhat** [comment]
@rohanagarwal94 I could take up this issue as you probably have the Twitter feed to work upon.

**Comment by rohanagarwal94** [comment]
@shreyasnbhat unfortunately due to loklak server being down, I took up this issue and started working on it.

**Comment by rohanagarwal94** [comment]
![screenshot_2017-07-15-21-58-59-796_com miui home](https://user-images.githubusercontent.com/13241256/28240985-05bc098e-69a9-11e7-8343-e7c87cd50c96.png)

@iamareebjamal the bookmark currently looks like this unlike the screenshot I posted in the issue which is when the widget created is smaller. I feel removal of bookmark is not useful here since user might delete it by mistake. The update issue as pointed out by @shreyasnbhat gets solved in #1815. I think it it should not be enhanced anymore. @Shailesh351 @arp95 @mahikaw any idea you guys have which could enhance it?

**Comment by iamareebjamal** [comment]
I think it's good as is. Perhaps adding track info would be too much. Let's hear from others as well

**Comment by shreyasnbhat** [comment]
@rohanagarwal94 You could remove the bullets. Add a divider for the list items and make the Bookmark widget text color to white. Rest looks fine.

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
