### ISSUE TITLE
Showing download button only when the apk is available

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-droidgen#1819]
**Actual Behaviour**

Currently showing of the download button in the apk-generator when the apk isnt available. Show download button only when apk is available.

**Expected Behaviour**

Doing above changes.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/33

**Comment by iamareebjamal** [comment]
This was working fine as far as I remember, when did it break?

**Comment by arp95** [comment]
no i mean hiding the button until apk is not available. right now we are showing it in disabled mode.

**Comment by iamareebjamal** [comment]
Oh, OK

**Comment by arp95** [comment]
clsoing this due to majority in favour of disabling the download button instead of hiding it.
