### ISSUE TITLE
Write UI layer test 

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-droidgen#1835]
**Actual Behaviour**

There are no UI layer tests currently.

**Expected Behaviour**

There should be UI layer Espresso tests for different activities to ensure the app is not crashing while traversing through activities.

**Would you like to work on the issue?**
Yes.

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 

https://github.com/fossasia/open-event-android/milestone/34

**Comment by iamareebjamal** [comment]
@mahikaw Assume no connectivity during UI tests so that they don't fail if CI is having connectivity issues

**Comment by mahikaw** [comment]
@iamareebjamal Yes I'm planning on using mockito.

**Comment by vedantrathore** [comment]
@mahikaw Are you still working on this? if not I'd like to start with this issue.

**Comment by iamareebjamal** [comment]
@vedantrathore Please carry on :smile:

**Comment by leeyh20** [comment]
Hello! is @vedantrathore still working on this?

**Comment by iamareebjamal** [comment]
No @leeyh20. You can take it up if you want

**Comment by leeyh20** [comment]
@iamareebjamal Since I'm done with #2031, I will try working on this!

**Comment by iamareebjamal** [comment]
@leeyh20 We don't have enough unit tests, unit tests are easier to write and hold higher priority than UI testing because there will be no way to test and mock UI if there is an untestable core layer
