### ISSUE TITLE
Adding feature of user feedback and live questions for speakers

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-droidgen#1838]
**Actual Behaviour**

Currently there is no way to give feedback of sessions or to ask live questions/give suggestions at real time to speakers.

**Expected Behaviour**

There should be features to rate the sessions after they end as well as give real time feedback of an ongoing session.
This needs to be integrated to server, which will be possible after server shifts to API implementation completely.

**Comment by mahikaw** [comment]
@iamareebjamal @niranjan94 @the-dagger @mananwason Please add a the tags 'later' and 'feature' to it.

**Comment by mayank8318** [comment]
@iamareebjamal I didnt see the API for this in the Heroku docs. Is there a plan for implementing this as this is a necessary addition and will also require user auth.

**Comment by iamareebjamal** [comment]
If the API is not providing it, all we can do is wait. There are already requests for various features on API guys and they take them organically as required
