### ISSUE TITLE
Adding user authentication option in apk-generator

### ISSUE THREAD

**Issue by arp95** [fossasia/open-event-droidgen#1839]
**Actual Behaviour**

As the user authentication option is added we can now add an option to enable user authentication.

**Expected Behaviour**

Doing the above changes.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/35

**Comment by mahikaw** [comment]
@arp95 Could you please describe the issue in some more detail. I don't exactly get the issue.
