### ISSUE TITLE
Layout customisation in app generator

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-droidgen#1845]
**Actual Behaviour**

We currently have colour customisation in app generator. 
**Expected Behaviour**

To further the issue of app customisation, there should be layout customisation as well. 
The app generator will provide option of layouts for tracks, sessions, micro locations etc and on the basis of what the user wants, it will generate an application.

**Would you like to work on the issue?**
Yes. 

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 
https://github.com/fossasia/open-event-android/milestone/35

**Comment by shreyasnbhat** [comment]
Options for layouts as in what?

**Comment by mahikaw** [comment]
Remember how we were all discussing about which UI layout should be most suited for tracks fragments(say) in #1649 I think it is best for the user to decide what sort of layout he/she wants to have through app generator.

**Comment by leeyh20** [comment]
@iamareebjamal should we continue with this?

**Comment by iamareebjamal** [comment]
We don't have any customisable layout as of now, but if you have any idea, you can share with us
