### ISSUE TITLE
Bug in deciding upcoming for different time zones

### ISSUE THREAD

**Issue by mahikaw** [fossasia/open-event-droidgen#1846]
**Actual Behaviour**

The current implementation of the feature doesn't take care of different time zones.

**Expected Behaviour**

The feature should take into account different time zones as well. 

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 
https://github.com/fossasia/open-event-android/milestone/35

**Comment by ahsanbarkati** [comment]
I am a newbie here at FOSSASIA. I want to solve this issue, Please guide me how to give it a start.

**Comment by Shailesh351** [comment]
Hi @ahsanbarkati welcome :smile: 

You may be confuse with this issue. Upcoming-Ongoing session feature was added in https://github.com/fossasia/open-event-android/pull/1822. 

Currently Upcoming and ongoing feature has some bugs.

- Create one more method `isOngoingSession()` in https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/java/org/fossasia/openevent/utils/DateService.java

- Use above methods and make required changes in https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/java/org/fossasia/openevent/activities/TrackSessionsActivity.java#L158  (For upcoming session start and end time should be after current time. And for on going start time should be before current time and end time should be after current time) 

- Make required changes here also https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/java/org/fossasia/openevent/adapters/SessionsListAdapter.java#L150 

Thanks, Feel free to ask doubt if you have. :smile:

**Comment by ahsanbarkati** [comment]
Here in https://github.com/fossasia/open-event-android/blob/development/android/app/src/main/java/org/fossasia/openevent/utils/DateService.java
```
public static boolean isUpcomingSession(Date start, Date end, Date current) {
        return ((start.before(current) || start.equals(current)) && (end.after(current) || end.equals(current)));
    }
```
The above method returns true if current date lies between start and end date. Then how is this a method for upcoming session? Please correct me if I am wrong.

**Comment by Shailesh351** [comment]
Exactly. That's where you have to made changes.
For upcoming  : start.after(current) &&  end.after(current)
For ongoing : start.before(current) && end.after(current)

**Comment by ahsanbarkati** [comment]
I created the required isOngoingSession() method and also corrected the isUpcomingSession().
Moving on to the next file.
I want to know what these variables represent (upcomingPosition, countOngoing, ongoingPosition ,countUpcoming)
```
try {
                    Date start = DateConverter.getDate(trackSession.getStartsAt());
                    Date end = DateConverter.getDate((trackSession.getEndsAt()));
                    Date current = new Date();
                    if (DateService.isUpcomingSession(start, end, current)) {
                        ongoingPosition = countUpcoming;
                        break;
                    } else if (start.after(current)) {
                        upcomingPosition = countOngoing;
                        break;
                    } else flag += 1;
                    countUpcoming += 1;
                    countOngoing += 1;
                } catch (ParseException e) {
                    e.printStackTrace();
                }
```

**Comment by Shailesh351** [comment]
ongoingPosition, upcomingPosition are class variable. countOngoing, countUpcoming  are local variable.  countOngoing, countUpcoming sets the value of of ongoingPosition, upcomingPosition.

ongoingPosition/upcomingPosition is used to scroll recyclerview to the Ongoing/Upcoming session.
