### ISSUE TITLE
Compound drawable is not supported in API < 21

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-droidgen#1867]
**Actual Behaviour**

~Currently in session_item and other places. Drawable is shown using ImageView. 
`<LinearLayout><ImageView/><TextView/><LinearLayout/>`~
Compound drawable is not supported in API < 21

**Expected Behaviour**

~Drawable can be combined with TextView using drawableLeft attribute.
`<TextView  drawableLeft="abc"/>`~
Remove compound drawable to support API < 21

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

[Milestone 14](https://github.com/fossasia/open-event-android/milestone/37)

**Comment by iamareebjamal** [comment]
This won't work on older devices as we are using vector drawables

**Comment by Shailesh351** [comment]
@iamareebjamal It should work fine on older devices also. We have already enabled Vector drawable backward compatibility.

https://developer.android.com/guide/topics/graphics/vector-drawable-resources.html#vector-drawables-backward-solution

https://github.com/fossasia/open-event-android/blob/development/android/app/build.gradle#L34

**Comment by iamareebjamal** [comment]
Compound drawables don't work with vector drawables on older devices. You can try though

**Comment by Shailesh351** [comment]
@iamareebjamal You are right. This tiny library fixes it https://github.com/a-tolstykh/textview-rich-drawable. Should we use it ?

**Comment by iamareebjamal** [comment]
I think another library for this is a bit too much for something which is not broken. If we enable databinding in future, we'll be able to do it without the library

**Comment by Shailesh351** [comment]
Okay.  There are other files(User Auth) which uses compound drawable. I'll change it from `<TextView  drawableLeft="abc"/>` to  `<LinearLayout><ImageView/><TextView/><LinearLayout/>` :+1:
