### ISSUE TITLE
App not showing download dialog on emulator

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-droidgen#1868]
**Actual Behaviour**

Currently we are using `ping` utility to check active internet connection. But ping don't work on Android emulator. Because of it app is not showing download dialogue on emualtor.

https://stackoverflow.com/questions/14234873/can-i-use-ping-command-in-the-android-emulator
 
**Expected Behaviour**

User other method for checking active internet connection. i.e. Using HttpUrlConnection and checking response code. 

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

[Milestone 14](https://github.com/fossasia/open-event-android/milestone/37)

**Comment by iamareebjamal** [comment]
I think we should remove the ping util completely and set a custom timeout. It takes a lot of time on real devices too to even show the dialog. We should just show it if the network is present and the request will timeout if it is slow

**Comment by Shailesh351** [comment]
@iamareebjamal So `NetworkStateReceiverListener` will have only two methods networkAvailable() and networkUnavailable().

All the tasks we are currently doing in the activeConnection() will be moved to networkAvailable() and inactiveConnection() to networkUnavailable(). 
Right?

**Comment by iamareebjamal** [comment]
Yes
