### ISSUE TITLE
Use ThreeTenABP for timezone handling

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-droidgen#1875]
Timezone of event and user is not handled correctly as of now. Follow [this](https://github.com/fossasia/open-event-orga-app/commit/e8cc06f55d159d39511d001f37984327bac0fa36) and make required changes to the project

@Shailesh351 You mentioned working on this, right? :smile:

**Comment by Shailesh351** [comment]
Yes, Working on it 😄
