### ISSUE TITLE
Memory leak in SpeakersDetailActivity

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-droidgen#1885]
**Actual Behaviour**

SpeakersDetailActivity has memory leak because of poor CustomTabService implementation. 

**Expected Behaviour**

Fix memory leak, remove redundant code and reuse Util method for CustomTabService.

**Screenshot of the issue**

![screenshot-1503118892747](https://user-images.githubusercontent.com/18264684/29483687-9f8f06ca-84c9-11e7-9788-017e9a9a0dbd.jpg)
 

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

[Milestone 16](https://github.com/fossasia/open-event-android/milestone/39)

**Comment by hardik124** [comment]
@Shailesh351  Can i work on this?

**Comment by Shailesh351** [comment]
@hardik124 Sure go ahead

**Comment by hardik124** [comment]
@Shailesh351 , there are no getter and setters defined for data/Speaker.class, still they have been referenced in SpeakersDetailActivity. Can you please confirm this?

**Comment by iamareebjamal** [comment]
@hardik124 They are generated by [lombok](https://projectlombok.org/) at compile time

**Comment by Shailesh351** [comment]
@hardik124 Status? We need to fix it asap :smile:

**Comment by hardik124** [comment]
Hi @Shailesh351  , sorry , i got sick actually and have just recovered. I will fix it ASAP .

**Comment by Shailesh351** [comment]
Don't be sorry. It's okay. No Problem. :smile_cat:

**Comment by hardik124** [comment]
@Shailesh351  can you please tell me a way to add mock speakers?

**Comment by hardik124** [comment]
@Shailesh351, Can you tell me what is the use of CustomTabsSession? After removing it, I changed the code in the following way to remove the leak.
![screenshot from 2017-08-23 13-45-47](https://user-images.githubusercontent.com/6649948/29605730-9e43466c-8809-11e7-965c-502320158c0b.png)
does this look good?

**Comment by hardik124** [comment]
@Shailesh351  can I go ahead with this fix?

**Comment by Shailesh351** [comment]
@hardik124 Actually we don't need CustomTabClient and all. Just one util method (Utils.setUpCustomTab(Context context, String url)) will handle all. 

Current implementation for opening Speaker's social media links is so poor. That's why I have mentioned in the issue to remove redundant code.

You can completely remove SpeakerIntent class and on clicking social media button you just need to pass url in the setUpCustomTab method. Remove all the unnecessary code.

No poor implementation with unnecessary code No memory leak  :sweat_smile: 

Please ask if you have any other query :smile:
