### ISSUE TITLE
SignUp Not Working

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-droidgen#1911]
**Actual Behaviour**
After installing the app when I go to the SignUp option and fill the details it throws error 
"Error in signing up".

**Expected Behaviour**
It should signup successfully.

**Steps to reproduce it**

Setup the app and go to the SignUp page from the navigation drawer

**LogCat for the issue**

12 19:53:53.734 26012-31555/org.fossasia.openevent D/OkHttp: --> POST http://abc/users http/1.1 (204-byte body)
09-12 19:53:53.739 26012-31555/org.fossasia.openevent D/OkHttp: <-- HTTP FAILED: java.net.UnknownHostException: Unable to resolve host "abc": No address associated with hostname
09-12 19:53:53.750 26012-26012/org.fossasia.openevent D/AuthUtil: java.net.UnknownHostException: Unable to resolve host "abc": No address associated with hostname

**Screenshots of the issue**
![screenshot_2017-09-12-19-44-19](https://user-images.githubusercontent.com/20026440/30332564-2dcc31f6-97f8-11e7-8407-4f3da82a07e4.png)

**Would you like to work on the issue?**

YES

**Comment by iamareebjamal** [comment]
Actually, you have to first add a correct API link. The API URL in debug message is  http://abc/ which is wrong

**Comment by codedsun** [comment]
@iamareebjamal  what shall be done for this issue?

**Comment by iamareebjamal** [comment]
Yes, please look into why it is happening. It shouldn't be. Thanks

**Comment by TarunISCO** [comment]
Same issue while signing up.

**Comment by codedsun** [comment]
@TarunISCO I will be working on this issue today...and will be sending the PR Asap.

**Comment by iamareebjamal** [comment]
@codedsun Should this issue be closed now?

**Comment by codedsun** [comment]
@iamareebjamal Yes :)
