### ISSUE TITLE
Opening Live Feed links within the app using customTab

### ISSUE THREAD

**Issue by manav-mj** [fossasia/open-event-droidgen#1912]
**Actual Behaviour**
The links (like the facebook link) in the Live Feed list-items open in chrome (uses Implicit Intent).

**Expected Behaviour**
The links should open within the app like the social media links on the homepage (should use CustomTabsIntent).

**Steps to reproduce it**
1. Go to Live Feed from navigation drawer.
2. Click the link in the item cards.

**Would you like to work on the issue?**
Yes.

**Comment by scandindian** [comment]
@iamareebjamal @the-dagger  What do you think about this? 

I think a user may want to do more things with live feed item that can not be done in the app itself, like opening multiple tabs or bookmarking.

**Comment by iamareebjamal** [comment]
Yeah, IMO it should be launching an intent dialog instead. Which may allow user to choose whether to open in browser or within app

**Comment by manav-mj** [comment]
@heysadboy @iamareebjamal @the-dagger Should I go ahead with this issue?

**Comment by scandindian** [comment]
@manav-mj Yes, please go ahead.
