### ISSUE TITLE
[App UI]  Smooth shared element transition of speaker's image in SpeakersList Fragment

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-droidgen#1913]
**Actual Behaviour**

Individual Speaker Intent is opening directly.

**Expected Behaviour**

Individual speaker intent should open with a shared element transition of the image of the speaker.

**Steps to reproduce it**

Just a small addition of transition type to the images present in the items of the Recycler view  in SpeakersList fragment and even in the Image View present in SpeakerDetails activity.

**Screenshots of the issue**

![alon2](https://user-images.githubusercontent.com/28607714/30433954-854b8300-9983-11e7-9805-e8b1eadf9aa6.png)

On clicking a card -> A new intent shoots up without a smooth transition.

![alone](https://user-images.githubusercontent.com/28607714/30433842-29ffb638-9983-11e7-93d1-8990163a0584.png)

**Would you like to work on the issue?**
Yes

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue?

**Comment by iamareebjamal** [comment]
Sure, please go ahead. Just keep in mind that the image being loaded in Speaker Detail page is loaded from another URL than the thumbnail on Speakers page. So strategy can be to show the shared element transition on thumbnail to the extended app bar and then allow the full image to load

**Comment by dreadpool2** [comment]
Yeah I will keep that in mind. Thanks 😃
