### ISSUE TITLE
Duplicate links in Live Feed list-items

### ISSUE THREAD

**Issue by manav-mj** [fossasia/open-event-droidgen#1914]
**Actual Behaviour**

Some of the list-items in Live Feed have links in the message as well as a separate TextView with link. 
So as a result the link is duplicated.

**Expected Behaviour**

One of the links should be removed

**Screenshots of the issue**

![screenshot_2017-09-15-02-31-33-318_org fossasia openevent](https://user-images.githubusercontent.com/22222147/30457053-9bf0d6ce-99c3-11e7-96cf-1ed9df9d87dc.png)

**Would you like to work on the issue?**

Yes

**Comment by scandindian** [comment]
@manav-mj Yes, please do remove the non-clickable ones.
