### ISSUE TITLE
Do not show stale notifications

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-droidgen#1917]
**Actual Behaviour**

Notifications are shown for past sessions when a user bookmarks it

**Expected Behaviour**

Notifications should only be shown for upcoming events

**Steps to reproduce it**

Bookmark any past event

**Would you like to work on the issue?**

No

**Comment by manav-mj** [comment]
@iamareebjamal i would like to work on the issue

**Comment by iamareebjamal** [comment]
@manav-mj Please go ahead
