### ISSUE TITLE
Show search suggestions in MainActivity

### ISSUE THREAD

**Issue by manav-mj** [fossasia/open-event-droidgen#1922]
**Actual Behaviour**

Search does not show suggestion when in MainActivity (AboutFragment)

<img src = "https://user-images.githubusercontent.com/22222147/30671094-e3e94e98-9e82-11e7-9f70-919a2b5edb4e.png" height = "480px" width="270px">

**Expected Behaviour**

Search should show suggestions when in MainActivity (AboutFragment), like in the SearchActivity

<img src = "https://user-images.githubusercontent.com/22222147/30671170-2a136110-9e83-11e7-95a5-f2820b0671e5.png" height = "480px" width="270px">

**Would you like to work on the issue?**

Yes.

**Comment by scandindian** [comment]
@manav-mj Sounds great, please do.

**Comment by manav-mj** [comment]
@heysadboy @iamareebjamal should we open `SearchActivity` on search icon click or show suggestions in the `AboutFragment` itself ?

**Comment by iamareebjamal** [comment]
The second option would be complicated IMO

**Comment by iamareebjamal** [comment]
The second option would be complicated IMO

**Comment by scandindian** [comment]
I agree with @iamareebjamal

**Comment by manav-mj** [comment]
@iamareebjamal @heysadboy  
I have submitted the PR making the required changes for the first option
