### ISSUE TITLE
Schedules are downloaded even on clicking No

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-droidgen#1923]
**Actual Behaviour**

On first launch of app, a dialog box appears and says *Do You want to update to the latest schedule now?" and even on clicking *NO* it downloads the event info.

**Expected Behaviour**

A snackbar should be shown to the user of the error .

**Steps to reproduce it**

Uninstall the app and then install it and then on the dialog box click *NO* ,the event infos are still downloaded

**LogCat for the issue**

09-21 21:41:03.610 21952-21952/org.fossasia.openevent I/BaseActivity: Activity onResume
09-21 21:41:07.319 21952-21952/org.fossasia.openevent D/MainActivity: JSON parsing started
09-21 21:41:07.561 21952-21952/org.fossasia.openevent D/DownloadCounter: 7 counter
09-21 21:41:07.557 21952-21967/org.fossasia.openevent I/art: Background sticky concurrent mark sweep GC freed 8039(666KB) AllocSpace objects, 13(208KB) LOS objects, 0% free, 13MB/13MB, paused 6.033ms total 156.640ms
09-21 21:41:07.680 21952-21962/org.fossasia.openevent W/art: Suspending all threads took: 85.506ms
09-21 21:41:07.699 21952-21967/org.fossasia.openevent I/art: Background partial concurrent mark sweep GC freed 3722(230KB) AllocSpace objects, 6(2MB) LOS objects, 39% free, 11MB/19MB, paused 3.253ms total 111.511ms
09-21 21:41:07.719 21952-21967/org.fossasia.openevent W/art: Suspending all threads took: 19.530ms
09-21 21:41:07.731 21952-21952/org.fossasia.openevent W/nAnnotationIntrospector: Unable to load JDK7 annotation types; will have to skip
09-21 21:41:08.116 21952-21962/org.fossasia.openevent W/art: Suspending all threads took: 22.123ms
09-21 21:41:08.163 21952-21952/org.fossasia.openevent W/System.err: WARNING: could not load Java7 Path class
09-21 21:41:08.661 21952-21962/org.fossasia.openevent W/art: Suspending all threads took: 67.042ms
09-21 21:41:08.955 21952-21952/org.fossasia.openevent D/RealmDataRepository: Saved Event
09-21 21:41:08.964 21952-21952/org.fossasia.openevent D/RealmDataRepository: Saved Event
09-21 21:41:08.969 21952-21952/org.fossasia.openevent I/Choreographer: Skipped 96 frames!  The application may be doing too much work on its main thread.
09-21 21:41:08.979 21952-22827/org.fossasia.openevent D/MainActivity: Saved event from JSON
09-21 21:41:11.241 21952-21952/org.fossasia.openevent D/RealmDataRepository: Saved Sessions
09-21 21:41:11.244 21952-22872/org.fossasia.openevent D/MainActivity: Saved event from JSON
09-21 21:41:12.348 21952-21952/org.fossasia.openevent D/RealmDataRepository: Saved Speakers
09-21 21:41:12.361 21952-22904/org.fossasia.openevent D/MainActivity: Saved event from JSON
09-21 21:41:12.542 21952-21952/org.fossasia.openevent D/RealmDataRepository: Saved Tracks
09-21 21:41:12.544 21952-22260/org.fossasia.openevent D/MainActivity: Saved event from JSON
09-21 21:41:12.577 21952-21966/org.fossasia.openevent I/art: WaitForGcToComplete blocked for 20.969ms for cause HeapTrim
09-21 21:41:12.603 21952-21952/org.fossasia.openevent D/RealmDataRepository: Saved Sponsors
09-21 21:41:12.605 21952-22827/org.fossasia.openevent D/MainActivity: Saved event from JSON
09-21 21:41:12.628 21952-21952/org.fossasia.openevent D/RealmDataRepository: Saved Locations
09-21 21:41:12.630 21952-22872/org.fossasia.openevent D/MainActivity: Saved event from JSON
09-21 21:41:12.656 21952-21952/org.fossasia.openevent D/RealmDataRepository: Saved Session Types
09-21 21:41:12.657 21952-22904/org.fossasia.openevent D/MainActivity: Saved event from JSON
09-21 21:41:12.658 21952-21952/org.fossasia.openevent D/DownloadCounter: 1 Event Info 7
09-21 21:41:12.660 21952-21952/org.fossasia.openevent D/DownloadCompleteHandler: Progress : 14.285715 Downloaded Event Info…
09-21 21:41:12.676 21952-21952/org.fossasia.openevent I/Choreographer: Skipped 221 frames!  The application may be doing too much work on its main thread.
09-21 21:41:12.756 21952-21952/org.fossasia.openevent D/DownloadCounter: 2 Sessions 7
09-21 21:41:12.757 21952-21952/org.fossasia.openevent D/DownloadCompleteHandler: Progress : 28.571430 Downloaded Sessions…
09-21 21:41:12.759 21952-21952/org.fossasia.openevent D/DownloadCounter: 3 Speakers 7
09-21 21:41:12.760 21952-21952/org.fossasia.openevent D/DownloadCompleteHandler: Progress : 42.857143 Downloaded Speakers…
09-21 21:41:12.762 21952-21952/org.fossasia.openevent D/DownloadCounter: 4 Tracks 7
09-21 21:41:12.763 21952-21952/org.fossasia.openevent D/DownloadCompleteHandler: Progress : 57.142860 Downloaded Tracks…
09-21 21:41:12.766 21952-21952/org.fossasia.openevent D/DownloadCounter: 5 Sponsors 7
09-21 21:41:12.767 21952-21952/org.fossasia.openevent D/DownloadCompleteHandler: Progress : 71.428574 Downloaded Sponsors…
09-21 21:41:12.771 21952-21952/org.fossasia.openevent D/DownloadCounter: 6 Locations 7
09-21 21:41:12.772 21952-21952/org.fossasia.openevent D/DownloadCompleteHandler: Progress : 85.714287 Downloaded Locations…
09-21 21:41:12.775 21952-21952/org.fossasia.openevent D/DownloadCounter: 7 Session Types 7
09-21 21:41:12.776 21952-21952/org.fossasia.openevent D/DownloadCompleteHandler: Progress : 100.000000 Downloaded Session Types…
09-21 21:41:12.870 21952-21952/org.fossasia.openevent D/MainActivity: Data loaded from JSON
09-21 21:41:13.126 21952-21962/org.fossasia.openevent W/art: Suspending all threads took: 27.109ms
09-21 21:41:13.151 21952-22928/org.fossasia.openevent D/OkHttp: --> GET https://graph.facebook.com/fossasia?access_token=1786614831603417|DWqP48Lm77hBqCQDWVsq4lFixuo http/1.1
09-21 21:41:13.268 21952-21952/org.fossasia.openevent D/ButterKnife: Looking up binding for org.fossasia.openevent.adapters.viewholders.SocialLinkViewHolder
09-21 21:41:13.269 21952-21952/org.fossasia.openevent D/ButterKnife: HIT: Loaded binding class and constructor.
09-21 21:41:13.278 21952-21952/org.fossasia.openevent D/ButterKnife: Looking up binding for org.fossasia.openevent.adapters.viewholders.SocialLinkViewHolder
09-21 21:41:13.278 21952-21952/org.fossasia.openevent D/ButterKnife: HIT: Cached in binding map.
09-21 21:41:13.284 21952-21952/org.fossasia.openevent D/ButterKnife: Looking up binding for org.fossasia.openevent.adapters.viewholders.SocialLinkViewHolder
09-21 21:41:13.284 21952-21952/org.fossasia.openevent D/ButterKnife: HIT: Cached in binding map.
09-21 21:41:13.290 21952-21952/org.fossasia.openevent D/ButterKnife: Looking up binding for org.fossasia.openevent.adapters.viewholders.SocialLinkViewHolder
09-21 21:41:13.290 21952-21952/org.fossasia.openevent D/ButterKnife: HIT: Cached in binding map.
09-21 21:41:13.294 21952-21952/org.fossasia.openevent D/ButterKnife: Looking up binding for org.fossasia.openevent.adapters.viewholders.SocialLinkViewHolder
09-21 21:41:13.294 21952-21952/org.fossasia.openevent D/ButterKnife: HIT: Cached in binding map.
09-21 21:41:13.295 21952-21952/org.fossasia.openevent D/ButterKnife: Looking up binding for org.fossasia.openevent.adapters.viewholders.SocialLinkViewHolder
09-21 21:41:13.295 21952-21952/org.fossasia.openevent D/ButterKnife: HIT: Cached in binding map.
09-21 21:41:13.300 21952-21952/org.fossasia.openevent D/ButterKnife: Looking up binding for org.fossasia.openevent.adapters.viewholders.SocialLinkViewHolder
09-21 21:41:13.300 21952-21952/org.fossasia.openevent D/ButterKnife: HIT: Cached in binding map.
09-21 21:41:13.301 21952-21952/org.fossasia.openevent D/ButterKnife: Looking up binding for org.fossasia.openevent.adapters.viewholders.SocialLinkViewHolder
09-21 21:41:13.302 21952-21952/org.fossasia.openevent D/ButterKnife: HIT: Cached in binding map.
09-21 21:41:13.306 21952-21952/org.fossasia.openevent D/ButterKnife: Looking up binding for org.fossasia.openevent.adapters.viewholders.SocialLinkViewHolder
09-21 21:41:13.306 21952-21952/org.fossasia.openevent D/ButterKnife: HIT: Cached in binding map.
09-21 21:41:14.112 21952-22928/org.fossasia.openevent D/OkHttp: <-- 200  https://graph.facebook.com/fossasia?access_token=1786614831603417|DWqP48Lm77hBqCQDWVsq4lFixuo (961ms, 42-byte body)

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**
Yes !

**Target Milestone to solve the issue**

@iamareebjamal Kindly review.

**Comment by iamareebjamal** [comment]
Once you click no, can you please post the logs after it?

**Comment by codedsun** [comment]
@iamareebjamal Comment updated !

**Comment by iamareebjamal** [comment]
I think the schedule is not downloaded but parsed from the static JSON files in `assets`

**Comment by codedsun** [comment]
@iamareebjamal For the first launch of app, when the download is pressed to *No* where is the data coming from?

**Comment by iamareebjamal** [comment]
The static JSON files in `assets`

**Comment by codedsun** [comment]
Ok! Closing the issue then.
Thanks.
