### ISSUE TITLE
Simple smooth sliding animation of Event Bar

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-droidgen#1925]
**Actual Behaviour**

Direct visibility of the "Fossasia is the premier Free and Open Source Technology" is happening

**Expected Behaviour**

There should be smooth sliding down behaviour of the Event open bar

**Steps to reproduce it**

The animation process just needs to be changed.

**Screenshots of the issue**

![first](https://user-images.githubusercontent.com/28607714/30774984-90760d6e-a0a8-11e7-86e2-7205ffe93bc0.png)

transition to ->

![second](https://user-images.githubusercontent.com/28607714/30774982-8ad1051c-a0a8-11e7-9600-e3b7feba8927.png)

and vice-versa.

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue?

**Comment by scandindian** [comment]
That sounds great, please do @dreadpool2
