### ISSUE TITLE
Wrong indentation of text in Session detail activity

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-droidgen#1930]
**Actual Behaviour**

The text shown in each line is wrongly indented  (The track text and below four lines).

**Expected Behaviour**

The text shown in each line should be correctly indented.

**Steps to reproduce it**

We need to change the way the text is represented by changing layout orientations.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

![screenshot_20170925-144937](https://user-images.githubusercontent.com/28607714/30809271-c930f368-a21e-11e7-94dd-42ab0a4c0be5.png)

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue?

**Comment by heysadboy** [comment]
I think it should be like this

Track      : XYZ
Location : XYZ

**Comment by scandindian** [comment]
@dreadpool2 How do you plan to indent it then?

**Comment by dreadpool2** [comment]
@heysadboy I plan to indent them in such a way: (Track2 is date for example)
Track -&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xyzaaaaa
Track2 -&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xyza
Track3 -&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xyza
Track4 -&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xyzaaa
