### ISSUE TITLE
Update for UI of Login and Signup Activity

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-droidgen#1959]
**Actual Behaviour**

The UI is not up to the recent trends.

**Expected Behaviour**

The UI should be updated.

**Would you like to work on the issue?**

Yes !.

@iamareebjamal Review this!

**Comment by pk-03** [comment]
yes>>>bro

**Comment by iamareebjamal** [comment]
Please propose the changes when you create an issue so that it is easy for reviewers to know what you plan to do

`The UI is not up to the recent trends.` and `The UI should be updated.` is vague
