### ISSUE TITLE
Implement Internationalization

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-droidgen#1962]
In order to use the app in different languages, please implement internationalization capabilities.

**Comment by rishz** [comment]
@mariobehling Shall I work on integrating the project with [Weblate](https://weblate.org)?

**Comment by codedsun** [comment]
@mariobehling  Can i take this issue

**Comment by srv-twry** [comment]
Taking this one.

**Comment by rishabchirania** [comment]
@srv-twry i can implement this with weblate?....should i take this issue

**Comment by dr0pdb** [comment]
@rishabchirania Sorry, i don't have enough information on this issue to suggest you. 
May be @iamareebjamal can help you :smile:
