### ISSUE TITLE
Broken link to LinkedIn in MainActivity

### ISSUE THREAD

**Issue by 97k** [fossasia/open-event-droidgen#1969]
**Actual Behaviour**

Link to FOSSASIA on LinkedIn is broken

**Expected Behaviour**

The Link should be correct

**Steps to reproduce it**

Open the app, click on the LinkedIn icon, it will not lead to FOSSASIA.

**Screenshots of the issue**

![giphy 2](https://user-images.githubusercontent.com/21143936/32186960-8c860270-bdc9-11e7-9884-bd24344669cd.gif)

**Would you like to work on the issue?**

Yes

**Comment by scandindian** [comment]
@aditya98ak Did you check the log trace for the link? Try if it opens in browser manually anyways and put an error check to see if the link exists before opening it.

@iamareebjamal @niranjan94 @the-dagger I can't edit the event from the server if this is because of that. Can you help please?

**Comment by iamareebjamal** [comment]
It's not an app issue if the event provider has wrong information set. If the link is not present, we can hide the button

**Comment by Shailesh351** [comment]
I think problem is with LinkedIn app it is not handling url properly. And
also if link is not present then it will not show button.

>

**Comment by raju249** [comment]
Is this issue still available ? @aditya are bus98ak 
I can take this up if you are busy with something else :smile:
