### ISSUE TITLE
Unnecessary elements showing up in shared text

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-droidgen#1971]
**Actual Behaviour**

Unnecessary elements are showing up while sharing the session details.

**Expected Behaviour**

Relevant Details must show up while sharing details.

**Steps to reproduce it**

We parse the JSON elements correctly and align the details correctly.

**Screenshots of the issue**
![screenshot_20171101-022526](https://user-images.githubusercontent.com/28607714/32248592-2265647e-beac-11e7-9876-dedc61ee15aa.png)
![screenshot_20171101-022536](https://user-images.githubusercontent.com/28607714/32248593-22930c94-beac-11e7-8c67-0f5200e7551d.png)

**Would you like to work on the issue?**
Yes, I will work on this issue

**Comment by scandindian** [comment]
@dreadpool2 Yes, please go on.

**Comment by dr0pdb** [comment]
@dreadpool2 Are you working on it ? If not, then i would like to take it.

**Comment by dreadpool2** [comment]
@srv-twry Yeah please go on!.

**Comment by dreadpool2** [comment]
@srv-twry Is this issue resolved?

**Comment by dr0pdb** [comment]
No, if you intend to work on it then you can
