### ISSUE TITLE
Display TimeZone with time

### ISSUE THREAD

**Issue by 97k** [fossasia/open-event-droidgen#1974]
**Actual Behaviour**

Currently, no time zone is shown to user

**Expected Behaviour**

TImezone should be shown i.e SST/UTC/IST.

**Screenshots of the issue**

![temp](https://user-images.githubusercontent.com/21143936/32362037-05703772-c08c-11e7-81ba-c7966b1994b5.jpeg)

**Would you like to work on the issue?**

Yes.
@heysadboy Can I work on this?

**Comment by Shailesh351** [comment]
@aditya98ak Sounds good. It will look good in Action bar like "Schedule (GMT +05:30)". Please go ahead :smile:

**Comment by heysadboy** [comment]
@aditya98ak I think it would be implicit from the place where the conference is happening and putting IST/UTC in front of dates everywhere is repetitive. 

I noticed that here the date is displayed in 24 hour format while in Tracks it is 12 hour format. Display it in 12 hour format too in Schedules, maybe that could be more informative.

**Comment by dr0pdb** [comment]
@iamareebjamal Can i take this since the PR has been inactive for a long time ?

**Comment by iamareebjamal** [comment]
Please go ahead

**Comment by dr0pdb** [comment]
I am not sure adding the timezone to the Action bar works.


![screenshot_2018-01-22-21-50-36-51](https://user-images.githubusercontent.com/21277837/35231772-a8c8991a-ffbf-11e7-9b92-bcfc47fbdc01.png)

**Comment by iamareebjamal** [comment]
Try subtitle
