### ISSUE TITLE
Snackbar 'undo' button visibility low

### ISSUE THREAD

**Issue by S2606** [fossasia/open-event-droidgen#1977]
**Actual Behaviour**

'undo' button color is bit darker which decreases its visibility

**Expected Behaviour**

To use lighter shades of red for greater visibility

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/18497513/32547754-6f848832-c47b-11e7-8b21-46acb86e2a12.png)

**Would you like to work on the issue?**

Yes

**Comment by scandindian** [comment]
@S2606 I think we can change the transparency of colors to make them visible on darker color. Can you experiment it.

No
![style-color-usability-alpha3-161116](https://user-images.githubusercontent.com/22588035/32655862-7d600bb4-c635-11e7-8157-4de963830479.png)

Yes
![style-color-usability-alpha4-161116](https://user-images.githubusercontent.com/22588035/32655875-8903b3a8-c635-11e7-95b9-3e36548500c9.png)


See the legibility part.
https://material.io/guidelines/style/color.html#color-usability

**Comment by S2606** [comment]
@heysadboy Sure..
