### ISSUE TITLE
Improve UI of Call for Speaker

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-droidgen#1979]
**Actual Behaviour**

The current UI of Call for Speaker has bugs and can be improved.

**Expected Behaviour**

Better UI.

**Steps to reproduce it**

Click Call for Speaker from the menu.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/22395998/32554927-5d11da06-c4c1-11e7-8c6d-5d587d795a60.png)

**Would you like to work on the issue?**

Yes

**Comment by scandindian** [comment]
@mayank8318 Please also describe the changes you propose to make the UI better.

**Comment by mayank8318** [comment]
@heysadboy Sorry I did not do that. I have mentioned it in the PR.
I will keep this in mind next time.
Thanks.
