### ISSUE TITLE
App crashes on selecting or bookmarking an event having a null value

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-droidgen#1983]
**Actual Behaviour**

App crashes on bookmarking or selecting an event in sessionDetails Activity having a null value

**Expected Behaviour**

App should not crash

**Steps to reproduce it**

Select schedule. Click on open tech. click on the  first event.

**LogCat for the issue**

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.fossasia.openevent.data.Track.getFontColor()' on a null object reference

**Screenshots of the issue**

![ezgif com-video-to-gif 19](https://user-images.githubusercontent.com/20878145/32624062-22e403d4-c5ae-11e7-948f-8703e2f6095e.gif)

**Would you like to work on the issue?**

Yes

**Comment by scandindian** [comment]
@nikit19 Seems legit, put an error check there and use accent color if the track color value is null.

**Comment by nikit19** [comment]
@heysadboy I guess just putting an error check is enough because the track is null and not the color value. I'll send a PR soon and then you can review it. Thanks
