### ISSUE TITLE
No option to undo Bookmark change in the Tracks section

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-droidgen#1987]
**Actual Behaviour**

Currently the Snackbar in Tracks when a bookmark is added or removed does not have an UNDO action.

**Expected Behaviour**

There should be an UNDO action like the one in Bookmarks section.

**Steps to reproduce it**

Open Tracks
Select any option
Bookmark / Remove bookmark for any event.

**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/22395998/32661885-8b4356aa-c64e-11e7-84f9-c663d8597d05.png)

![image](https://user-images.githubusercontent.com/22395998/32661892-90f7e8ae-c64e-11e7-830b-fd5ae0df90c8.png)

**Would you like to work on the issue?**

Yes

**Comment by scandindian** [comment]
@mayank8318 Yes please add undo functionality. Also see the color according to this issue https://github.com/fossasia/open-event-android/issues/1977

**Comment by mayank8318** [comment]
@heysadboy I will wait for that PR to be merged so that there are no merge conflicts.
Is that okay?

**Comment by scandindian** [comment]
@mayank8318 It's okay.

**Comment by mayank8318** [comment]
@heysadboy @S2606 Regarding #1977 should I do it in this issue itself?

**Comment by iamareebjamal** [comment]
@mayank8318 It's better to keep issues and PRs separate 😄

**Comment by mayank8318** [comment]
@iamareebjamal Should I work on that issue as it doesn't have a PR yet?

**Comment by iamareebjamal** [comment]
Yes please
