### ISSUE TITLE
Cursor position should be at the end of the editText

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-droidgen#1988]
**Actual Behaviour**

Currently when we open the editProfileActivity,the cursor is positioned at the beginning  of the name editText and the user has to the move the cursor to the end and then edit his/her name.

**Expected Behaviour**
Cursor should be present at the end of the name editText

**Steps to reproduce it**

Sign up.
Go to editProfile activity

**Screenshots of the issue**
![screenshot_20171110-193711](https://user-images.githubusercontent.com/20878145/32661959-d8ed6fe4-c64e-11e7-871a-3ef21a028c91.png)

**Would you like to work on the issue?**

Yes

**Comment by scandindian** [comment]
Yes, please work on this.
