### ISSUE TITLE
SnackBar hides floatingActionButton in schedule fragment

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-droidgen#1989]
**Actual Behaviour**

If we add or remove a bookmark in schedule fragment,the snackBar hides the floatingActionButton

**Expected Behaviour**

The floatingActionButton should shift upwards when a snackBar message is displayed

**Steps to reproduce it**

Go to schedule fragment and add a bookmark

**Screenshots of the issue**

![screenshot_20171110-234314](https://user-images.githubusercontent.com/20878145/32672565-85525e58-c671-11e7-9885-3e0d9e330059.png)

**Would you like to work on the issue?**

Yes

**Comment by scandindian** [comment]
@nikit19 Yes, please work on this.
