### ISSUE TITLE
Add view that change visibility of password in password box

### ISSUE THREAD

**Issue by 97k** [fossasia/open-event-droidgen#1990]
**Actual Behaviour**

Currently, there is no option to view typed password in sign_up/logging_in!

**Expected Behaviour**

A small view should be there, clicking on which shows the typed password.

**Would you like to work on the issue?**

Yes!

**Comment by scandindian** [comment]
@aditya98ak You can see this for reference

![login](https://user-images.githubusercontent.com/22588035/32687883-09b1d1a4-c6ec-11e7-972d-30e17b04db80.png)

**Comment by 97k** [comment]
@heysadboy Yes, I got that, Thanks :smile:

**Comment by iamareebjamal** [comment]
Fixed by #1998
