### ISSUE TITLE
Same line of code written twice

### ISSUE THREAD

**Issue by ahsan44411** [fossasia/open-event-droidgen#1993]
Same line of code is written twice in Main Activity. Here is a screen shot of it.
![inshallah](https://user-images.githubusercontent.com/30962013/32697758-9ac8dcfa-c7b9-11e7-88d3-7fdb1543e896.png)

I would like you take this issue and remove the extra line

**Comment by scandindian** [comment]
@ahsan44411 Yes, please work on this.
