### ISSUE TITLE
CheckBoxes are not cleared on pressing the back button

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-droidgen#1995]
**Actual Behaviour**

In the schedule fragment if we click on the filter floating action button , select some checkboxes and press the back button. 
And then on clicking on the filter floating action button again,we see that the checkboxes are still in selected state

**Expected Behaviour**

CheckBoxes should be cleared if the user has pressed the back button

**Steps to reproduce it**

Open schedule fragment.
Click on filter fab.
select some checkboxes.
click the back button.
click on the filter fab again

**Screenshots of the issue**

![ezgif com-video-to-gif 22](https://user-images.githubusercontent.com/20878145/32730311-ac0adfa6-c8ac-11e7-9db6-d52f0cce8fbb.gif)

**Would you like to work on the issue?**

Yes

**Comment by yashLadha** [comment]
Are you currently working on this issue?

**Comment by nikit19** [comment]
Yeah. Almost finished
