### ISSUE TITLE
Hide/Show password icon in Login and SignUp Layout

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-droidgen#1997]
**Actual Behaviour**

Toggle Password hide/show button is not present

**Expected Behaviour**

It should be there.

**Steps to reproduce it**

On Signup and Login Activity, it can be seen

**Would you like to work on the issue?**

Yes!

**Comment by 97k** [comment]
@codedsun I already created this issue #1990

**Comment by codedsun** [comment]
@aditya98ak I sent the pull request... no problem if we can reference that issue with this PR.

@heysadboy

**Comment by scandindian** [comment]
@codedsun close this issue and iterate from #1990 ~
