### ISSUE TITLE
apk link in description box not working

### ISSUE THREAD

**Issue by iamjaspreetsingh** [fossasia/open-event-droidgen#2006]
The apk link given in the description box is not working
It is giving error 404.
Please check
![new tab - google chrome 30-11-2017 00_29_10](https://user-images.githubusercontent.com/30948046/33393972-e0e8217c-d566-11e7-8a9b-580082be30c8.png)

**Comment by iamareebjamal** [comment]
Fixed. Thanks for notifying 😄
