### ISSUE TITLE
Improve frond end of Android APK generator

### ISSUE THREAD

**Issue by scandindian** [fossasia/open-event-droidgen#2007]
**Actual Behaviour**

Currently the[ web page](https://droidgen.eventyay.com/) to generate android APK looks nice but very basic. Modern design practices such as 

- Ripples on touching button
- Shadow around the button making it look elevated
- Using material colours in the navbar and other elements

and other tweaks that can improve the aesthetic of the page are missing.

![screenshot from 2017-12-03 17-46-17](https://user-images.githubusercontent.com/22588035/33525293-ca99c666-d852-11e7-87d4-3d93f44b85f8.png)

**Expected Behaviour**

Beautify the web page to make it look more attractive and appealing. By improving

- Colour Scheme
- User Experience
- User Interface
- Overall Aesthetic

**Steps to reproduce it**

You can find files here https://github.com/fossasia/open-event-android/tree/development/apk-generator/v2. Look for HTML and CSS files in the folder.

**Would you like to work on the issue?**

This advanced issue is meant for Google Code-In students.

**Comment by mayank8318** [comment]
@iamareebjamal @heysadboy Can I give this issue a try?

**Comment by scandindian** [comment]
Sure @mayank8318.

**Comment by mayank8318** [comment]
@heysadboy @iamareebjamal If I add any resources to the assets folder, I need to redo the `celery` part right?
Also am I free to use images which are not restricted by copyright issues?

**Comment by iamareebjamal** [comment]
I don't think you need to restart the server if you add static assets.

Yes you can use images, but try to use SVGs or webfonts and limit yourself to a point it looks standard and not bloated
