### ISSUE TITLE
UI scaling error In About Fragment

### ISSUE THREAD

**Issue by S2606** [fossasia/open-event-droidgen#2011]
**Actual Behaviour**

![screenshot-1512732101971](https://user-images.githubusercontent.com/18497513/33763892-35e2db18-dc38-11e7-9471-ab158149b5b1.jpg)
![screenshot-1512732061713](https://user-images.githubusercontent.com/18497513/33763900-3d1d76ae-dc38-11e7-8276-c9b3088f103b.jpg)

**Expected Behaviour**

Only the Event open text view should change its position based on clicking the expand button

**Would you like to work on this?**

Yes

**Comment by S2606** [comment]
@iamareebjamal @heysadboy What do you think?

**Comment by iamareebjamal** [comment]
Sorry I didn't understand the issue completely?
