### ISSUE TITLE
Fix padding in Copyright dialog

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-droidgen#2018]
**Actual Behaviour**

Padding is very less in copyright dialog. 

**Expected Behaviour**

Keep same padding as Call For speakers Dialog

**Screenshots of the issue**

Copy right
![screenshot-1513179018372](https://user-images.githubusercontent.com/18264684/33946911-0b81010a-e049-11e7-88cf-612a1cdb9def.jpg)

Call For Speakers
![screenshot-1513179039697](https://user-images.githubusercontent.com/18264684/33946927-135d3326-e049-11e7-8e7b-fb824e773791.jpg)

**Comment by nikit19** [comment]
I would like to work on this! :smile:
