### ISSUE TITLE
Improve UI of Speakers Fragment

### ISSUE THREAD

**Issue by Shailesh351** [fossasia/open-event-droidgen#2019]
**Actual Behaviour**

Currently speaker's list is in Grid Layout

**Expected Behaviour**

Improve UI of Speakers Fragment using LinearLayout with Sticky Headers. 
https://youtu.be/omN3ojMUYnI

**Comment by nikit19** [comment]
@Shailesh351 I would like to work on this

**Comment by Shailesh351** [comment]
@nikit19  Sure. Thanks :smile:
