### ISSUE TITLE
APKs not being generated

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-droidgen#2020]
**Actual Behaviour**

Travis build scripts were based on relative paths and changing of directories and hence, after the PR #2013, it can't reference to built files

**Expected Behaviour**

Either travis scripts should reference correct relative paths or preferably use absolute paths so that the directory containing scripts do not have any significance in build process

**Reference**

Last build on Travis : https://travis-ci.org/fossasia/open-event-android/builds/316025286?utm_source=github_status&utm_medium=notification

**Comment by Shailesh351** [comment]
@iamareebjamal I think path of generated apks is changed in latest build tools.
![screenshot from 2017-12-14 14-15-00](https://user-images.githubusercontent.com/18264684/33983230-637f9d22-e0d9-11e7-8a69-97fc0359a93f.png)


So we need to update paths in generate_apks.sh from `app/build/outputs/apk/app-{fdroid/googleplay}-{debug/release}.apk` to `app/build/outputs/apk/{fdroid/googleplay}/{debug/release}/app-{fdroid/googleplay}-{debug/release}.apk`

OR Update the path of generated apks

**Comment by Shailesh351** [comment]
Also https://travis-ci.org/fossasia/open-event-android/builds/316025286#L2179 is uses rm to delete generated apks. But now apks are in sub directories so we need to use `rm -R` to delete all the sub directories and files

**Comment by iamareebjamal** [comment]
Thanks @Shailesh351 😄
