### ISSUE TITLE
Create ViewModel for LocationActivity

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2026]
**Actual Behaviour**

There isn't any ```ViewModel``` for the ```LocationActivity```.

**Expected Behaviour**

There should be one.

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes!

**Target Milestone to solve the issue**

NA

**Other information**

Parent issue #2015

**Comment by Kartikdot** [comment]
I would like to take this one up. Thank you.

**Comment by dr0pdb** [comment]
@Kartik2016 Are you working on it ? It would be nice to know the progress. If you aren't then i would like to take this up.

**Comment by Kartikdot** [comment]
I am sorry i got busy with my college project, hence couldn't work on this. If this issue isn't holding up any other work or any other issues...i would like to continue to work on it. I'll update here with the progress or a PR this weekend.

**Comment by dr0pdb** [comment]
Sure go ahead.
