### ISSUE TITLE
Create ViewModel for the DayScheduleFragment

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2031]
**Actual Behaviour**

There is no ViewModel for the DayScheduleFragment

**Expected Behaviour**

There should be one.

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes!

**Target Milestone to solve the issue**

NA

**Other information**

Parent issue #2015

**Comment by codedsun** [comment]
@srv-twry Can I work on this issue?

**Comment by dr0pdb** [comment]
@codedsun Please go ahead :)

**Comment by samagra14** [comment]
@codedsun Are you still working on the issue?

**Comment by dr0pdb** [comment]
@samagra14 I think it has been way too long without any updates. Please go ahead and finish this off. We have a lot of pending work and we should finish creating the ViewModel quickly so that we can move to the next step.

**Comment by samagra14** [comment]
@srv-twry I have started working on this issue. I will submit a PR positively by tomorrow.

**Comment by samagra14** [comment]
@srv-twry I found that the code is very poorly documented. There are no exclusive comments for methods as such and to get an idea of any method, we have to look at its implementation. I hope work should be done in that direction also as it will get difficult as the size grows. Please let me know your views on this.

**Comment by dr0pdb** [comment]
@samagra14 Please create a new issue for it and we can discuss it there. This isn't the best place for it.

**Comment by samagra14** [comment]
@srv-twry I have opened a PR. Please take a look.

**Comment by leeyh20** [comment]
Hi, I would like to try working on this issue, will reference other ViewModels too. Can start tomorrow :)
