### ISSUE TITLE
Improve the UI for the SpeakerDetailsActivity

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2033]
**Actual Behaviour**

There is scope of improvement in the UI of SpeakerDetailsActivity

**Expected Behaviour**

The UI should be improved.

**Steps to reproduce it**

NA

**LogCat for the issue**

NA

**Screenshots of the issue**

![screenshot_2017-12-21-17-56-21-77](https://user-images.githubusercontent.com/21277837/34255845-830c1522-e678-11e7-9f3d-a60f3a933040.png)

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

NA

**Proposed changes**

1. The Speaker's bio & social media should each be in enclosed in a card view.
2. Header's indicating bio(About me) , contact(Contact me) and seminar's(Seminars) can be inserted before the respective card views.

**Comment by dr0pdb** [comment]
@iamareebjamal Please review

**Comment by iamareebjamal** [comment]
Please go ahead
