### ISSUE TITLE
Add the login button in the Navigation drawer

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2034]
**Actual Behaviour**

There is a sign up button but no login button in the Navigation drawer.

**Expected Behaviour**

There should also be a login button in the navigation drawer.

**Steps to reproduce it**

Open navigation drawer.

**LogCat for the issue**

NA

**Screenshots of the issue**

![screenshot_2017-12-21-18-18-18-60](https://user-images.githubusercontent.com/21277837/34256516-b9c5065c-e67b-11e7-995a-b274ac51d01d.png)

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

NA

**Proposed changes**

There should also be a login button in the navigation drawer, which would open the login activity.
Although there is an option to open the login activity from the signup activity but i believe there should be a direct way to open it. Opening signup activity everytime just to open login activity isn't according to usual trends. 

@iamareebjamal @the-dagger Please review.

**Comment by iamareebjamal** [comment]
We can change it to login, and show the standard login/signup activity, but adding another entry for same activity is just redundant

**Comment by dr0pdb** [comment]
Yeah that will do

**Comment by iamareebjamal** [comment]
@srv-twry Let's help close old bugs first
