### ISSUE TITLE
Text appears smaller in toolbar on rotation

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-droidgen#2036]
**Actual Behaviour**

Currently if we keep our phone in landscape mode and open any activity,the text size of the toolbar is decreased (on rotating the screen normally ie after opening the activity, the text size remains the same)

**Expected Behaviour**

The text size should be same in all cases.

**Steps to reproduce it**

Keep your phone in landscape mode.
Open any activity.

**Screenshots of the issue**

![screenshot_20171222-125933](https://user-images.githubusercontent.com/20878145/34289569-25ae52d6-e719-11e7-8580-942251c7860b.png)

![ezgif com-video-to-gif 27](https://user-images.githubusercontent.com/20878145/34289533-fd8282a0-e718-11e7-9f65-550ac89b49a3.gif)

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
@nikit19 Status?

**Comment by nikit19** [comment]
Will send the PR today
