### ISSUE TITLE
Add a cancel button in the Network not available dialog

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2041]
**Actual Behaviour**

When opening the application without internet connection, a dialog appears with title "Network not available" with one button "Ok" which directs the user to device Settings. There is no option to cancel and browse the application without network.

**Expected Behaviour**

There should be a "Cancel" button.

**Steps to reproduce it**

Switch off mobile data and wifi.
Open the application.

**LogCat for the issue**

NA

**Screenshots of the issue**

![screenshot_2017-12-22-23-14-16-22](https://user-images.githubusercontent.com/21277837/34307580-ca6521ce-e76e-11e7-83ad-b9337b04bfeb.png)

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

NA

**Proposed changes**

The dialog should also contain a "Cancel" button to close the dialog. Since it is possible to browse the application without network, the user should be allowed to do so. Infact since the dialog is ```cancellable```, it would be much better if user has an option right in front of him/her. 

@iamareebjamal @the-dagger Please review.

**Comment by the-dagger** [comment]
@srv-twry Sounds good, go ahead. 👍
