### ISSUE TITLE
Implement search query in the ViewModel for SpeakersListFragment

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2042]
**Actual Behaviour**

Currently the search query in most of the fragments is implemented inside the adapter.

**Expected Behaviour**

The search query should be implemented inside the ViewModel for SpeakersListFragment

**Steps to reproduce it**

NA.

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes, but after i am done with the rest of ```ViewModel```  PR's. Can be assigned to someone else in the mean time.

**Target Milestone to solve the issue**

NA

**Other information**

Please check the discussion out in this PR #2039

**Comment by iamareebjamal** [comment]
But this will mean unnecessary fetching from database for filtering data which is already present in memory @the-dagger

This will both be less performant and more resource intensive and slow. Filter method in adapter is explicitly used for this purpose 

Any advantage of this?

**Comment by the-dagger** [comment]
@iamareebjamal I am really not sure if using a list and filtering on it is a good idea.
I mean we will be going ahead with ROOM and later on a Paged List anyways, combine that with large number of speakers in the app (~300), not sure if going ahead, filtering on the list would be good.

What do you think?

**Comment by dr0pdb** [comment]
@the-dagger May i add something here ?

**Comment by the-dagger** [comment]
Sure, definitely 👍

**Comment by dr0pdb** [comment]
I think we can implement the query inside the ViewModel without querying the database more than once.
The complete list will be fetched from the database and will be stored inside the ```ViewModel``` and we can store another list that will store only the filtered values according to the search query and return it when required.

**Comment by iamareebjamal** [comment]
@the-dagger Any interaction with database is always slower than operation in memory. Querying with LIKE statement is even slower and we are not implementing throttling, so on each keypress of user, 300 items are being searched again, and then modelled into POJOs, new objects are being created, list is being cleared and add items are inserted. This will also cause frequent GC calls to collect old redundant objects. Furthermore, with database filtering we cannot implement fuzzy search in future.

**Comment by the-dagger** [comment]
@iamareebjamal Ok, alright.
But let's atleast move the logic for filtering away from the Adapter, instead put the filter in the ViewModel instead and keep the adapter here free from any such logic.

Sounds good?

**Comment by iamareebjamal** [comment]
Yeah that would be great
