### ISSUE TITLE
Use default RealmLiveData wrapper

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-droidgen#2062]
https://academy.realm.io/posts/android-architecture-components-and-realm/

Instead of managing it in ViewModel, use the official method

**Would you like to work on the issue?**
No

**Comment by mayank8318** [comment]
@iamareebjamal This should start by changing the Realm queries right?

**Comment by iamareebjamal** [comment]
No need to change the realm queries, they can be wrapped over using the function mentioned in the article

**Comment by mayank8318** [comment]
@iamareebjamal Ok got it. I would like to work on this.

**Comment by iamareebjamal** [comment]
Please go ahead
