### ISSUE TITLE
Improve the "No upcoming session dialog" UI

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2075]
**Actual Behaviour**

The UI for the "No upcoming session dialog" needs improvement.

**Expected Behaviour**

The dialog UI should be improved.

**Steps to reproduce it**

Open LocationsActivity -> Click on any location -> click on upcoming locations icon on the toolbar -> If there is no upcoming session, then the dialog will pop up 

**Screenshots of the issue**

![screenshot_2017-12-31-11-55-43-38](https://user-images.githubusercontent.com/21277837/34459891-d833d5fa-ee23-11e7-8d82-5979f1e12186.png)

**Would you like to work on the issue?**

Yes

**Proposed changes**

Using an alert dialog with a single positive button would be more consistent with the Android design principles.

@iamareebjamal @the-dagger Views ?

**Comment by SparshWadhwa** [comment]
I would like to work on this issue. May I?
@srv-twry

**Comment by dr0pdb** [comment]
@SparshWadhwa I suggest you wait since the maintainers are probably busy. Once they get time, they will approve this issue first, whether it is worth it or not. Then you can go ahead with it.

**Comment by iamareebjamal** [comment]
This screenshot is of current UI or proposed one?

**Comment by dr0pdb** [comment]
Current UI

**Comment by iamareebjamal** [comment]
Yup. Please go ahead and use standard layout
