### ISSUE TITLE
Allow users to cancel the LiveFeed download

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2076]
**Actual Behaviour**

There is no option to cancel the LiveFeed download once the user open FeedFragment.

**Expected Behaviour**

There should also be an option to cancel the download, if the user wants.

**Steps to reproduce it**

Open FeedFragment

**Would you like to work on the issue?**

Yes

**Proposed changes**
In the progress dialog, add a cancel button to cancel loading and go back.

**Comment by dr0pdb** [comment]
@iamareebjamal What do you think ?

**Comment by iamareebjamal** [comment]
Yup, please go ahead
