### ISSUE TITLE
Add ViewModel for DayScheduleFragment

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-droidgen#2080]
**Actual Behaviour**

There is no viewmodel for DayScheduleFragment

**Expected Behaviour**

There should be a viewmodel.

**Would you like to work on the issue?**
Yes

**Comment by dr0pdb** [comment]
@dreadpool2 Before creating an issue, please check if the issue about the same topic already exists.
Duplicate of #2031

**Comment by dreadpool2** [comment]
Oh!  I am extremely sorry !! I coudn't find the issue! @srv-twry

**Comment by dr0pdb** [comment]
@dreadpool2 No problem :) Kindly close it. If you want , you can work on #2051 . Kindly drop a comment their if you want to go ahead.

**Comment by dreadpool2** [comment]
Ok cool! &#128402;&#128402;
