### ISSUE TITLE
Remove unnecessary try/catch in FeedAdapter

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2085]
**Actual Behaviour**

There is an unnecessary try/catch block in FeedAdapter. For more info check [this](https://github.com/fossasia/open-event-android/pull/2084#pullrequestreview-86201298) comment.

**Expected Behaviour**

It isn't required.

**Steps to reproduce it**

NA

**Would you like to work on the issue?**

Yes

**Comment by divyabaid16** [comment]
I would like to work on this issue.

**Comment by dr0pdb** [comment]
@divyabaid16 Sure, go ahead.

**Comment by iamareebjamal** [comment]
@srv-twry I think this has been fixed now by #2102 ?

**Comment by dr0pdb** [comment]
@iamareebjamal No, actually i didn't make these changes since @divyabaid16 had already opened the PR before me. Should i make it in #2102 ?

**Comment by iamareebjamal** [comment]
No, I'll merge this after conflicts are resolved
