### ISSUE TITLE
No limit for number of characters in first name and last name of user

### ISSUE THREAD

**Issue by khokharnikunj8** [fossasia/open-event-droidgen#2092]
**Actual Behaviour**
We are able to set first name of too many characters which leads to some unexpected behavior..

![screenshot_2018-01-06-10-05-26](https://user-images.githubusercontent.com/22648147/34636626-ff00e572-f2cb-11e7-874c-137a596dd908.png)
<br/>
![screenshot_2018-01-06-10-03-05](https://user-images.githubusercontent.com/22648147/34636641-3a72e740-f2cc-11e7-9030-9af907dec093.png)

<br/><br/>

**Expected Behaviour**

There should be some limit in number of characters in first name and last name .

![screenshot_2018-01-06-10-21-47](https://user-images.githubusercontent.com/22648147/34636643-50caba40-f2cc-11e7-9865-1a4157a2681c.png)

<br/><br/>

**Steps to reproduce it**

We can limit number of characters to 32 for each first name and last name.

**Would you like to work on the issue?**

YES

**Target Milestone to solve the issue**

```
android:maxLength="32"
```

**Comment by iamareebjamal** [comment]
It's alright to enforce it here but it really should be implemented at the API level instead

Because it's of no use restricting something which is allowed by the API. As the app is only a frontend and API is the backend

**Comment by khokharnikunj8** [comment]
@iamareebjamal  I agree with you... but at-least for android we should limit the characters.

**Comment by iamareebjamal** [comment]
What if a few months later, the server decides to use 64 character limit or something else. This will create an unnecessary issue in the app. We can have a small discussion with them before enforcing standards :smile:
