### ISSUE TITLE
Make images zoomable throughout the application

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2098]
**Actual Behaviour**

Currently only the images inside the FeedFragment are zoomable.

**Expected Behaviour**

All the images should be zoomable.

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
@srv-twry Should this be closed?

**Comment by dr0pdb** [comment]
I'll try and search for images that aren't zoomable yet. If not found, then i will close it.

**Comment by simarsingh24** [comment]
@srv-twry the profile photo inside "My Profile" should also be made zoomable! what do you think?

**Comment by dr0pdb** [comment]
Yes, should i work on it or do you want to work on it ?

**Comment by simarsingh24** [comment]
@srv-twry yeah, I would like to work on it :)
