### ISSUE TITLE
Reduce APK build size

### ISSUE THREAD

**Issue by S2606** [fossasia/open-event-droidgen#2100]
**Actual Behaviour**

APK build size is around 11.1 MB.

**Expected Behaviour**

Reduce the apk build size to 8.6 MB.

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
What is your proposed method of doing so?

**Comment by S2606** [comment]
@iamareebjamal I have used NDK abiFilters in build.gradle

**Comment by iamareebjamal** [comment]
We are using Google Play Signing method which automatically splits APKs when uploading to Google Play. Also it requires us to NOT split APKs ourselves for the signing and verification to work

**Comment by S2606** [comment]
Yes it does throw a warning but it just displays the changes took place.

**Comment by iamareebjamal** [comment]
Pardon, I couldn't understand what you meant to say
 

Please refer to this - https://support.google.com/googleplay/android-developer/answer/7384423?hl=en
