### ISSUE TITLE
Adding resize and crop features to user photo in Edit Profile

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-droidgen#2101]
**Actual Behaviour**

Selecting any photo makes it profile picture.

**Expected Behaviour**

Selecting photo should be allowed to crop, zoom etc.

**Steps to reproduce it**

Using library https://github.com/ArthurHub/Android-Image-Cropper

**Would you like to work on the issue?**

Yes!

**Comment by dr0pdb** [comment]
@simarsingh24 It has already been implemented in #2057 and is in for review.

**Comment by simarsingh24** [comment]
@srv-twry okay! 👍
