### ISSUE TITLE
Improve the shared text when session is shared by user 

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-droidgen#2103]
**Actual Behaviour**

"action_share" generates not properly formatted data.
Following is an example of shared message - 

> Session Track: Startup and Business Development 
Title: Community meets Business 
Start Time: Sat, 18 Mar 2017 
End Time: Sat, 18 Mar 2017
Speakers: Speaker = proxy[{id:2280},{name:Michael Meskes},{country:},{email:null},{organisation:credativ international GmbH},{photoUrl:https://storage.googleapis.com/eventyay.com/events/6/speakers/2280/photo/d1VEdTdEcT/540b4998-387d-414b-98da-419e73985d9e.png},{thumbnailImageUrl:https://storage.googleapis.com/eventyay.com/events/6/speakers/2280/thumbnail/SXhyNGVUcT/1d7ebed3-e5d3-4120-8075-b9627a534898.jpg},{smallImageUrl:https://storage.googleapis.com/eventyay.com/events/6/speakers/2280/small/cldhSWpSaH/5b9b2eb5-32fc-4cb9-ae66-1f572b866fad.jpg},{iconImageUrl:https://storage.googleapis.com/eventyay.com/events/6/speakers/2280/icon/Yld0NjgzL2/ef4366b0-28f0-49b1-a00f-e71ca2b5f7df.jpg},{twitter:},{linkedin:https://www.linkedin.com/in/michaelmeskes},{facebook:},{github:},{mobile:null},{website:https://www.credativ.co.uk/},{isFeatured:true},{city:},{longBiography:},{shortBiography:Michael Meskes is President and CEO of the credativ Group, an industry leader in free software services with offices in five countries. Its Open Source Support Centers employ leading members of a number of Open-Source projects. He has been Open-Source developer for twenty years working on different Open-Source projects among which Debian and PostgreSQL are most widely known. He also has done a lot of Open-Source related presentations on all sorts of events doing a lot of Open-Source evangelism.},{speakingExperience:null},{gender:Male},{position:CEO},{heardFrom:},{sponsorshipRequired:},{sessions:RealmList<Session>[3]}]
Location: Einstein (Floor 2)
Description:

**Expected Behaviour**
The data should be formatted properly.

**Steps to reproduce it**

Processing string before sending

**Would you like to work on the issue?**

Yes!

**Comment by dr0pdb** [comment]
@simarsingh24 Before creating any issue, please check if the issue already exists or not. 
Duplicate #1971 
Also i was already working on it. Since you've submitted the PR i will let this go but do take care from next time.

**Comment by simarsingh24** [comment]
Okay! I will make sure next time! Thanks :)
