### ISSUE TITLE
Create viewModel for TracksFragment

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-droidgen#2109]
**Actual Behaviour**

Tracks Fragment don't have any ViewModel

**Expected Behaviour**

Tracks Fragment should have a viewModel

**Would you like to work on the issue?**

YES

**Comment by nikit19** [comment]
This issue has already been raised here https://github.com/fossasia/open-event-android/issues/2045
and solved with this pull request https://github.com/fossasia/open-event-android/pull/2055
Please don't create issues that have already been raised
