### ISSUE TITLE
No Option To Reset Password

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-droidgen#2116]
**Actual Behaviour**

Their is no option to reset password

**Expected Behaviour**

Their should be an option for resetting password

**Would you like to work on the issue?**

Yes!

**Comment by mithlesh4257** [comment]
I like to work on the issue.

**Comment by codedsun** [comment]
@mithlesh4257 I am currently working on this, if possible try another issues which have not been taken by anybody.

**Comment by mithlesh4257** [comment]
@codedsun great :-)
