### ISSUE TITLE
Create ViewModel for UserProfileActivity

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2122]
**Actual Behaviour**

There is no ViewModel in UserProfileActivity

**Expected Behaviour**

There should be one.

**Would you like to work on the issue?**

Yes!

**Comment by simarsingh24** [comment]
@srv-twry since @SparshWadhwa haven't dropped any comment as per your conversation with him, can i start working on it ?

**Comment by dr0pdb** [comment]
@simarsingh24 Yeah, Please go ahead.
