### ISSUE TITLE
Create ViewModel for LoginActivity

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2124]
**Actual Behaviour**

There is no ViewModel in LoginActivity

**Expected Behaviour**

There should be one.

**Would you like to work on the issue?**

Yes!

**Comment by simarsingh24** [comment]
@srv-twry are you still working on it? If not can i work on it?

**Comment by dr0pdb** [comment]
Yes, Please go ahead.

**Comment by simarsingh24** [comment]
It doesn't look like we need ViewModel for LoginActivity right now. @iamareebjamal could you please go through it once and confirm does it really need a ViewModel? Thank you : )

**Comment by iamareebjamal** [comment]
@simarsingh24 Any fragment/activity that has an `if` or `for` which are not dealing with *only* views, needs to be refactored in a ViewModel

Right now, we are moving the obvious parts out. And soon, we will refactor more things from the areas which are already made into ViewModels. The plan is to remove every single logic related to API or any other business end from views

**Comment by dr0pdb** [comment]
Sorry about this, i linked the wrong issue.

**Comment by dr0pdb** [comment]
@simarsingh24 Are you working on it ? otherwise , i will take it on and finish it.

**Comment by simarsingh24** [comment]
@srv-twry since I haven't started yet, please go ahead :)
