### ISSUE TITLE
Create ViewModel for EditProfileActivity

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2125]
**Actual Behaviour**

There is no ViewModel in EditProfileActivity

**Expected Behaviour**

There should be one.

**Would you like to work on the issue?**

Yes!

**Comment by mani87** [comment]
@srv-twry what actually i have to do?
Only add a viewModel?

**Comment by dr0pdb** [comment]
Yes, you have to refactor the Activity to use MVVM architecture using the new architecture components. In case you don't know about them, you can always google and learn. You can also find sample implementations for other Activity/Fragment in the code.

**Comment by simarsingh24** [comment]
@srv-twry Would you mind if I start working on it?

**Comment by dr0pdb** [comment]
@simarsingh24 I think it will too early. It has only been 3 days since @mani87 claimed it. Let's give him some more time, atleast a week. If there is no response from him, then you can claim it.

**Comment by simarsingh24** [comment]
@srv-twry since its been more than a week and there is no update from @mani87, should i solve it !?

**Comment by dr0pdb** [comment]
Yes, please go ahead.
