### ISSUE TITLE
old password can be set when setting a new password

### ISSUE THREAD

**Issue by raj10071997** [fossasia/open-event-droidgen#2140]
**Actual Behaviour**

When we select to change the password the old password can be set again which should not happen.

**Expected Behaviour**

When trying to set the same password , the user must be alerted(using a snackbar) to set some other
password different from the old one.

**Would you like to work on the issue?**

yes

**Comment by iamareebjamal** [comment]
This is not defined in the API to disallow user from setting old password, so we can't add this feature

**Comment by raj10071997** [comment]
But this can be implemented in the app itself there is no need to implement it in the API. Just have to check whether the new password matches the previous one. Is it right??

**Comment by iamareebjamal** [comment]
It can be implemented but it should not be. We need 1:1 correspondence with API. There is webapp and Orga App as well. If a user can set old password there, and not here, it creates difference in UX of user and hence, either it is added at the API level or it should be left

**Comment by raj10071997** [comment]
ok , then i am closing this issue.
