### ISSUE TITLE
Make the Logging inside FilterableRealmLiveData more informative

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2148]
**Actual Behaviour**

Currently the code for logging inside FilterableRealmLiveData is 
``` Java
Timber.d("Filtering done total results %d", filteredList.size());
if (filteredList.isEmpty()) {
    Timber.e("No results published. There is an error in query. Check " + getClass().getName() + " filter!");
}
```

The ```getClass().getName()``` call will always return ```FilterableRealmLiveData``` which will make it unclear which Activity/Fragment associated with the FilterableRealmLiveData is actually logged here.

**Expected Behaviour**

 There should be a way for it to know the name of the ViewModel that this FilterableRealmLiveData is associated with so that it can log it's name which would make it more clear for us, the developers.

**Would you like to work on the issue?**

Yes

**Proposed changes**

We can pass the name of the ViewModel class as a parameter in the Constructor of the FilterableRealmLiveData class and store it and use it for logging.

@iamareebjamal What do you think is the right approach to handle this ?

**Comment by iamareebjamal** [comment]
Actually it is not an error if the filtered list is empty. When debugging, we can already see stacktrace and the fragment/activity where the behaviour is happening, so it is not so trivial to handle this and it will also change the structure of class, just for logging purposes
