### ISSUE TITLE
Improve UI of ViewHolder in SpeakersList RecyclerView

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2149]
**Actual Behaviour**

Currently the UI of ViewHolder is not good. The details of the Speaker is displayed on top of the Image of the Speaker. In some cases it leads to a problem as the face of the speaker is hidden completely by the description.

**Expected Behaviour**

The description shouldn't block the face of the speaker.

**Screenshots of the issue**

![screenshot_2018-01-17-12-26-24-42](https://user-images.githubusercontent.com/21277837/35029977-695903ae-fb83-11e7-9ca8-0f71ebf79407.png)
![screenshot_2018-01-17-12-27-08-38](https://user-images.githubusercontent.com/21277837/35029980-6a6854ca-fb83-11e7-8d11-a98c8c5fdcac.png)

One can see that in case of Mr. Alex Curreton Griffiths in the first image and Mrs/Miss Anwesha Das in the second image, the description almost completely blocks the face which makes having the image useless.

**Would you like to work on the issue?**

Yes

**Proposed Changes**

I believe we can move the description below the image of the speaker to avoid this issue.
@iamareebjamal Views ?

**Comment by simarsingh24** [comment]
@srv-twry why not we use google's contact app UI, what are your views on that?

**Comment by dr0pdb** [comment]
@simarsingh24 Can you add a screenshot of what you want to propose ?

**Comment by iamareebjamal** [comment]
Yes, I was thinking of the same problem. We can have a staggered grid UI with the textual information below the image and its background color calculated via Palette

**Comment by SparshWadhwa** [comment]
I wish to work on this issue ? May I? @srv-twry

**Comment by dr0pdb** [comment]
@SparshWadhwa Actually i am working on it. You can claim #2122 if you want. Thanks :smile: 
Drop a comment at that issue in case you want to.

**Comment by dr0pdb** [comment]
@iamareebjamal Can i use Staggered Grid view ? The issue with normal grid layout is variation in the size of the Speaker's textual information. 
1. I need to have the same size of image of each speaker
2. I also need to have same height of speaker's textual information.
3. I also need to have the whole item of the same size for all the speakers.

Satisfying all the three is difficult. Instead we can use Staggered Grid layout which will look good and also allow some differences in the heights.

**Comment by iamareebjamal** [comment]
Yes, I already suggested that above - `We can have a staggered grid UI`
