### ISSUE TITLE
Undo option is not shown when bookmark is added in ScheduleFragment

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-droidgen#2168]
**Actual Behaviour**

Undo option is unavailable when bookmark is added in ScheduleFragment

**Expected Behaviour**

Undo option should be present

**Steps to reproduce it**

Go to Schedule Fragment, add a bookmark

**Would you like to work on the issue?**

No

**Comment by nikit19** [comment]
I would like to work on this issue

**Comment by iamareebjamal** [comment]
Please go ahead

**Comment by simarsingh24** [comment]
@iamareebjamal same is true for TracksFragment, SpeakerDetailsActivity, LocationsFragment, and this clashes with issue #2157

**Comment by iamareebjamal** [comment]
@simarsingh24 that issue is about adding functionality, whereas, here Undo is shown to when bookmark is removed, but not when added, so it's a bug

**Comment by jindalAnuj** [comment]
Can I work on this issue also. As I have seen the issue is not assigned yet.

**Comment by simarsingh24** [comment]
@anideveloper @nikit19  is already working on it. please find some other issue :)
