### ISSUE TITLE
FOSSASIA color should be white.

### ISSUE THREAD

**Issue by mithlesh4257** [fossasia/open-event-droidgen#2170]
**Actual Behaviour**
FOSSASIA color is grey.
Please state here what is currently happening.

**Expected Behaviour**
FOSSASIA color should be pure white.

**Screenshots of the issue**
![whatsapp image 2018-01-19 at 6 18 13 pm](https://user-images.githubusercontent.com/22450186/35152063-d1b5bec8-fd46-11e7-89c4-a1f526e00d40.jpeg)

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
This is dependent on the event zip and API code, nothing to do with app
