### ISSUE TITLE
Cluttering in TracksSessionsActivity Results view

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-droidgen#2171]
**Actual Behaviour**

When there are no results found in the SearchView of `TrackSessionsActivity` and when it is refreshed by swiping down, cluttering of 'No Tracks Yet!' and 'No Results Found' occurs.

**Expected Behaviour**

The cluttering should not occur.

**Screenshots of the issue**

![videotogif_2018 01 19_19 40 41](https://user-images.githubusercontent.com/28607714/35154770-7871704a-fd51-11e7-8f9c-f5809c8d23ad.gif)

**Would you like to work on the issue?**

Yes !

**Comment by simarsingh24** [comment]
@dreadpool2 its been more than three weeks since you have raised this issue what is the status of this issue? Let me finish it off if you are busy with something else

**Comment by dreadpool2** [comment]
@simarsingh24 Looks like the situation has already been solved ! I am closing it
