### ISSUE TITLE
Nothing happens on selecting DownloadLatestData in menu

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-droidgen#2175]
**Actual Behaviour**

Selecting DownloadLatestData menu item does nothing once the data has been downloaded.

**Expected Behaviour**

It should show the data fetch dialog.

**Would you like to work on the issue?**

Yes

@iamareebjamal am not sure if it has been made that way !?

**Comment by dr0pdb** [comment]
@simarsingh24 Can you please attach a GIF of the issue. I didn't understand what you mean by 

> once the data has been downloaded.

**Comment by simarsingh24** [comment]
@srv-twry here is the gif you request for
![videotogif_2018 01 21_10 23 43](https://user-images.githubusercontent.com/16715499/35191009-28431682-fe96-11e7-8f39-1399b0e7a3f7.gif)

i am not sure if its a bug or its made that way?

**Comment by simarsingh24** [comment]
@srv-twry did you doing it? and should it open an download dialog again?

**Comment by iamareebjamal** [comment]
It should open again for downloading
