### ISSUE TITLE
No maximum limit on user password length

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-droidgen#2176]
**Actual Behaviour**

Password has a lower limit of >= 6 but no upper limit.

**Expected Behaviour**

There should be one.

**Would you like to work on the issue?**

Yes

@iamareebjamal what upper limit should be set for the password?

**Comment by Anandra-Singh** [comment]
I would like to work on this issue what should be the upper limit.

**Comment by iamareebjamal** [comment]
There should be no upper limit on the password. Read comment in this PR and issue for more info -> https://github.com/fossasia/open-event-android/pull/2093

**Comment by Anandra-Singh** [comment]
Ok I got it
