### ISSUE TITLE
Reformat code in all the required Classes and XML in the project

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2180]
**Actual Behaviour**

~~After #2179 , the code inside ```item_speaker.xml``` isn't properly formatted. It was left  untouched so that it's easier for the reviewer to review the code.~~
Reformat code in all the required classes and xml files in the project wherever needed.

**Expected Behaviour**

The code should be properly formatted.

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
Change to refactor the formatting of all required classes and XML in the project. Also only refactor those classes which have formatting issues because sometimes we intentionally deviate from standard style to make it more readable
