### ISSUE TITLE
Image in the Top Right Corner 

### ISSUE THREAD

**Issue by jindalAnuj** [fossasia/open-event-droidgen#2183]
**Actual Behaviour**

Image of the speakers at top right. It can be seen that only image of those speakers are wrong whom are positioned at 2nd position of new letter like A, C, F.

**Expected Behaviour**

image should have some proper margin like other speakers image

**Screenshots of the issue**

I have Marked the problem in Screenshots

![ScreenShot 1](https://user-images.githubusercontent.com/31108317/35192515-4a502cfa-feba-11e7-8721-27524a83e0ce.jpg)
![ScreenShot 2](https://user-images.githubusercontent.com/31108317/35192516-4a926cc8-feba-11e7-94af-343fce616f05.jpg)
![ScreenShot 3](https://user-images.githubusercontent.com/31108317/35192517-4ad4b646-feba-11e7-941c-0d2ba68415ee.jpg)

**Would you like to work on the issue?**

Yes

**Comment by dr0pdb** [comment]
@jindalAnuj I am working on moving from a grid layout to a staggered grid layout, so this issue will be solved in that PR automatically.
You can close this one :smile:
