### ISSUE TITLE
Change Sign Up Text

### ISSUE THREAD

**Issue by jindalAnuj** [fossasia/open-event-droidgen#2187]
**Actual Behaviour**

There  is Only SignUp Text in the Drawer

**Expected Behaviour**
there should be Signup/login as text such that everyone can

**Steps to reproduce it**

will change String in drawer.xml
Replace SignUp ---> Login/SignUp

**Would you like to work on the issue?**

Yes.

**Comment by dr0pdb** [comment]
Duplicate #2034 , so please close this.
Before creating any issue, please check if the issue exists or not.
