### ISSUE TITLE
Moving IS_DOWNLOAD_DONE logic inside methods in MainActivity

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-droidgen#2195]
**Expected Behaviour**

`IS_DOWNLOAD_DONE` should be set true or false inside the methods `downloadFromAssest()` and `downloadFromNetwork()` depending on whether these events were successful or not.

**Would you like to work on the issue?**

Yes

This way we don't have to put some value in it every time we call this function like we are doing here inside mainActivity
 `if (Utils.isBaseUrlEmpty()) {
            if (!SharedPreferencesUtil.getBoolean(ConstantStrings.IS_DOWNLOAD_DONE, false)) {
                downloadFromAssets();
                SharedPreferencesUtil.putBoolean(ConstantStrings.IS_DOWNLOAD_DONE, true);
            }`

@iamareebjamal your views?

**Comment by simarsingh24** [comment]
@iamareebjamal would it be a good idea?

**Comment by iamareebjamal** [comment]
Or, it should only be set to true if any of the method succeeds

**Comment by simarsingh24** [comment]
@iamareebjamal Yes! i am working on it :)
