### ISSUE TITLE
Refactor the SignUpActivityViewModel and remove all usage of Pair from ViewModels

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2200]
**Actual Behaviour**

Currently the Pair class is being used inside the SignUpActivityViewModel. Also it has code used by both itself and LoginActivity.

**Expected Behaviour**

Pair shouldn't be used as it is android specific. Also remove it's usage in other ViewModels.
Delete common methods and use the common code present in AuthUtils.

**Would you like to work on the issue?**

Yes

Can only be done after #2197 is merged.

**Comment by iamareebjamal** [comment]
Also remove from anywhere else if used

**Comment by dr0pdb** [comment]
Sure.
