### ISSUE TITLE
Addition of a scroll back fab in speakers list fragment

### ISSUE THREAD

**Issue by harshitbansal05** [fossasia/open-event-droidgen#2207]
**Actual Behaviour**

As is evident, the list of speakers is quite long and there is no way to go immediately very bottom or to the top(if at bottom).

**Expected Behaviour**

So there must be a **scroll to top** fab button as the user scrolls down. Other alternative is providing a list of alphabets on the right end, where tapping on a alphabet scrolls down to that part of the list.   

**Would you like to work on the issue?**

Yes!!

**Target Milestone to solve the issue**

Till which [milestone](https://github.com/fossasia/open-event-android/milestones) will you be fixing the issue? 

I would fix the issue in maximum two days time.

**Comment by harshitbansal05** [comment]
@srv-twry what's your opinion?

**Comment by dr0pdb** [comment]
@harshitbansal05 Yes, a good suggestion. @iamareebjamal What do you think ?

**Comment by iamareebjamal** [comment]
We can add an alphabetic fast scroll thumb as present in Contacts App

**Comment by harshitbansal05** [comment]
may I start working on it @srv-twry?

**Comment by dr0pdb** [comment]
Sure, please go ahead.

**Comment by harshitbansal05** [comment]
@srv-twry @iamareebjamal should i use the recycler view fast scroll widget or place a list of alphabets on the end, where tapping on a alphabet takes you to that part of that list.

**Comment by iamareebjamal** [comment]
Use FastScroller

**Comment by leeyh20** [comment]
@harshitbansal05  Are you still working on this? I want to try implementing this for a start because I'm new to the project, thanks! Sorry if you are still working on it.

**Comment by dr0pdb** [comment]
@leeyh20 I see you are a new contributor and want to contribute :smile: . We have a pending issue #2031 
How about you take that one and finish it. Please comment on that issue if you want to work on it.
It is slightly tough for beginners but definitely worth a shot. You can always ask for help.

**Comment by leeyh20** [comment]
@srv-twry Thanks for the suggestion!

**Comment by simarsingh24** [comment]
@harshitbansal05 it's been more than two weeks and there is no update from you regarding this issue? what is the status of this issue are you still working on it?

**Comment by harshitbansal05** [comment]
sorry @simarsingh24, i was involved in my mid term examinations, so could not contribute in the issue. I would try to do it soon...

**Comment by sriramr98** [comment]
@harshitbansal05 have the fix yet? Its been too long since the issue was opened and I'd like to finish it up.

**Comment by iamareebjamal** [comment]
Go ahead
