### ISSUE TITLE
UI bugs in Speakers fragment.

### ISSUE THREAD

**Issue by harshitbansal05** [fossasia/open-event-droidgen#2208]
**Actual Behaviour**

Text is cutting where the title of organisation is displayed. Also, it looks weird as if both titles are on the same layout. Also, due to difference in length of the organisations' name, one image shifts below the other. 

**Expected Behaviour**

Text must not be cut, and titles' layout must be properly separated. Also two images in a row must be at the same level.

**Screenshots of the issue**

![screenshot_2018-01-24-15-56-29-432_org fossasia openevent](https://user-images.githubusercontent.com/24504421/35327336-60963588-011f-11e8-9f91-087eba69f776.png)

**Would you like to work on the issue?**

Yes!!

**Target Milestone to solve the issue**

I would solve the issue most probably in about two days' time.

**Comment by dr0pdb** [comment]
@harshitbansal05 Please check for duplicates before creating issues. I am already working on improving the overall UI of this activity.
Duplicate: #2149

**Comment by harshitbansal05** [comment]
sorry, i did'nt have a look at it @srv-twry

**Comment by dr0pdb** [comment]
No problem, something to keep in mind from next time :smile: . Please close this now.
