### ISSUE TITLE
use liveDataWrappers and observers inside SessionDetailActivityViewModel

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-droidgen#2209]
**Actual Behaviour**

SessionDetailActivity is using onChangeListeners

**Expected Behaviour**

It should use Observers and LiveDataWrapper

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
Umm. If they are not to be used in views, they shouldn't be wrapped in LiveData, we are not really reacting to their changes
