### ISSUE TITLE
Keyboard should pop up automatically in Login and Register

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-droidgen#2222]
**Actual Behaviour**

Keyboard doesn't pop up automatically in login and register.

**Expected Behaviour**

It should pop up automatically.

**Steps to reproduce it**

Open Login or Register

**Would you like to work on the issue?**

Yes

**Comment by shivaraju07** [comment]
@mayank8318 if it automatically pop's up we can't see the sign-up button which is at the bottom of the screen.

**Comment by iamareebjamal** [comment]
Yes, let's not automate these many things. It's obtrusive to user experience
