### ISSUE TITLE
Write tests for SponsorsFragmentViewModel

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2224]
**Actual Behaviour**

The SponsorsFragmentViewModel has no tests written for it.

**Expected Behaviour**

There should be tests written for it.

**Would you like to work on the issue?**

Yes

**Parent issue**
#2017

**Comment by the-dagger** [comment]
@srv-twry Can we have a single parent issue for this?
Create a single PR that covers these test cases, no need to open multiple issues for every file.
I'm closing these issues.

**Comment by dr0pdb** [comment]
Sure.
