### ISSUE TITLE
There is no toast displayed while bookmarking in Speakers Section

### ISSUE THREAD

**Issue by shivaraju07** [fossasia/open-event-droidgen#2241]
**Actual Behaviour**

In Speakers Section under any selected person if we are bookmarking his/her sessions toast should be displayed. 

**Expected Behaviour**

Toast should be displayed like in other sections 

**Would you like to work on the issue?**

Yes

**Comment by nikit19** [comment]
This issue has already been created.
See this https://github.com/fossasia/open-event-android/issues/2221

**Comment by shivaraju07** [comment]
ya @nikit19 I got it.

**Comment by dr0pdb** [comment]
@shivaraju07 Please close this issue now that you know this issue already exists.
