### ISSUE TITLE
unnecessary underlined font in pop up while sort by function is used

### ISSUE THREAD

**Issue by shivaraju07** [fossasia/open-event-droidgen#2246]
**Actual Behaviour**

In Schedule section, while you are selecting for sort by option there you will see an underlined fonts of ASCENDING and DESCENDING 

**Expected Behaviour**

Expected is to disable the underlined font.

**Would you like to work on the issue?**

yes

**Screenshots of the issue**

![media-20180126](https://user-images.githubusercontent.com/18509469/35460407-ea1936c0-0309-11e8-8126-10de5d475c90.jpg)

**Comment by dr0pdb** [comment]
@shivaraju07 I think it has been done on purpose.

**Comment by shivaraju07** [comment]
then why the Descending word is not underlined.
If anyone of the options is selected it is highlighted by red color then why there is the use of underline?

**Comment by dr0pdb** [comment]
>  then why the Descending word is not underlined.

Only the selected word is underlined.

> If anyone of the options is selected it is highlighted by red color then why there is the use of underline?

Because there is no harm in adding two indicators.
If you still think it's a problem, then let's wait for @iamareebjamal to confirm.

**Comment by shivaraju07** [comment]
@srv-twry  Ok

**Comment by iamareebjamal** [comment]
I can't find the issue where this was discussed, it is not a standard to underline. But still we need to find the reason why it was done before reverting

**Comment by shivaraju07** [comment]
@iamareebjamal  should I remove it or should we add a `later` label to this issue.

**Comment by iamareebjamal** [comment]
Let's find the PR in which it was added, please use git blame or github feature for the same

**Comment by shivaraju07** [comment]
Ok @iamareebjamal

**Comment by shivaraju07** [comment]
It was created by Mayank Vaidya. But there is no use of the underline, Shall I create PR @iamareebjamal

**Comment by iamareebjamal** [comment]
In which PR was it created

**Comment by shivaraju07** [comment]
commit 08f28fca0d40efa0821f6679241bf32bc6291020
Author: Mayank Vaidya <mayank8318@gmail.com>
Date:   Mon Dec 11 21:51:55 2017 +0530

    fix: Provide Ascending/Descending option in sorting (#2008)
    
    - Add buttons to Sort dialog box for ascending / descending option
    
    Fixes #2005

**Comment by iamareebjamal** [comment]
Go ahead

**Comment by shivaraju07** [comment]
@iamareebjamal  views?
This is the final screenshot:
![new](https://user-images.githubusercontent.com/18509469/35484868-b5a3fee2-047c-11e8-96ad-aee05302362c.jpg)

**Comment by dr0pdb** [comment]
LGTM, Please open a PR for this :+1:
