### ISSUE TITLE
Tiles in Speaker section are uneven

### ISSUE THREAD

**Issue by shivaraju07** [fossasia/open-event-droidgen#2247]
**Actual Behaviour**

The tiles (which shows the name, photo) in speaker section are uneven

**Expected Behaviour**

I Think All should be given the same size to look nice

**Would you like to work on the issue?**
yes

**Screenshots of the issue**

![media-20180126](https://user-images.githubusercontent.com/18509469/35462628-c5fe1496-0312-11e8-9fb6-e47a517d938d.jpg)

**Comment by iamareebjamal** [comment]
This is intended. It is called Staggered Grid Layout

**Comment by dr0pdb** [comment]
@shivaraju07 They have been made uneven on purpose. It's a staggered layout. Please check #2149 and close this.
