### ISSUE TITLE
Upcoming function is not working in tracks section

### ISSUE THREAD

**Issue by shivaraju07** [fossasia/open-event-droidgen#2248]
**Actual Behaviour**

while selecting any track upcoming track is not working.

**Expected Behaviour**

I think it should be displayed as it is shown in location section.

**Would you like to work on the issue?**

Yes

**Comment by simarsingh24** [comment]
@shivaraju07 can you attach a gif for the same

**Comment by shivaraju07** [comment]
![gif-180127_125608](https://user-images.githubusercontent.com/18509469/35469775-b1eec414-0362-11e8-8bd7-c7c691f0f3b5.gif)
