### ISSUE TITLE
Uneven distribution of Tiles in Speakers Activity

### ISSUE THREAD

**Issue by shivaraju07** [fossasia/open-event-droidgen#2254]
**Actual Behaviour**

In speakers activity the tiles are uneven.

**Expected Behaviour**

I think all tiles should be given fixed size so that it looks nice.

**Would you like to work on the issue?**

Yes

**Screenshots of the issue**
![media-20180126](https://user-images.githubusercontent.com/18509469/35471096-e85b0cc0-037a-11e8-93fa-7ef2286be7b3.jpg)

@simarsingh24, @srv-twry  What do you think?

**Comment by dr0pdb** [comment]
Pardon, I couldn't understand what you mean by "tiles" ? 
Can you encircle it with some photo editor ?

**Comment by simarsingh24** [comment]
@shivaraju07  did you mean the photos are not aligned? like the beginning of the photographs in the same row should start together?

**Comment by shivaraju07** [comment]
@srv-twry I meant that the photos are not aligned in the same row as @simarsingh24 said .
They are not aligned in same row.
@simarsingh24  yes

**Comment by dr0pdb** [comment]
How is this issue different from #2247 ?

**Comment by dr0pdb** [comment]
@shivaraju07 Please don't abuse the freedom that you can create issues whenever you want. 
#2247 was also your issue and both me and the mentor told you the reason. I even gave you a link to the issue/PR where this was discussed. Please take care of this from next time.

**Comment by shivaraju07** [comment]
I apologise it won't happen next time.
