### ISSUE TITLE
unusual behaviour in Speaker list

### ISSUE THREAD

**Issue by jindalAnuj** [fossasia/open-event-droidgen#2256]
**Actual Behaviour**

A buggy speaker list with unusual behaviour the list is not alphabatically arranged sometimes data not get passed to speaker details activity. Also same data is shown multiple times

**Expected Behaviour**

there should be a alphabatic list with correct data to be shown 

**Screenshots of the issue**

<p align="center">
<img src="https://user-images.githubusercontent.com/31108317/35471690-60c5085e-0386-11e8-8600-0e1620b68e44.jpg" height = "480" width="270"><img src="https://user-images.githubusercontent.com/31108317/35471689-607a5b10-0386-11e8-8759-d31f4f871623.jpg" height = "480" width="270"> <img src="https://user-images.githubusercontent.com/31108317/35471688-6024bdae-0386-11e8-9e02-e4b344cead36.jpg" height = "480" width="270">
</p>

**Would you like to work on the issue?**
yes

**Comment by dr0pdb** [comment]
Have you made sure you have set the sorting option by "Speaker Name"
I am getting the correct order

![screenshot_2018-01-27-17-39-54-24](https://user-images.githubusercontent.com/21277837/35471847-69137d26-0389-11e8-9228-4dc3cea4cc8b.png)

About the duplicate items

I don't think it's an error in the application. There is a duplicate entry in the data itself. If you look closely, the Company/Organisation name is slightly different in both.

**Comment by simarsingh24** [comment]
@jindalAnuj  check the response given by the API itself and then compare it with what is populated on these views and if there is a mismatch then it would be an issue. 
PS: It worked fine for me.

**Comment by jindalAnuj** [comment]
@srv-twry @simarsingh24  yes they are alphabatical that was my mistake but the speaker with Hbd has some details which are empty sometimes and speaker with some **Other** name has some name which is encounterd only few times out of many attempts
