### ISSUE TITLE
MainActivity Unexpected Layout 

### ISSUE THREAD

**Issue by jindalAnuj** [fossasia/open-event-droidgen#2261]
**Actual Behaviour**

When FossAsia description is minimised layout looks awkward from bottom

**Expected Behaviour**

Layout should be even and user friendly

**Steps to reproduce it**

minimize the fossasia description

**Screenshots of the issue**

![ezgif com-video-to-gif 4](https://user-images.githubusercontent.com/31108317/35472854-e7ea7b00-039c-11e8-9a3a-10ecc8b34f60.gif)

**Would you like to work on the issue?**

yes

**Comment by iamareebjamal** [comment]
What do you mean by minimize?

**Comment by jindalAnuj** [comment]
@iamareebjamal by minimize i mean when hiding Fossasia description changes happen in bottom part as shown in screenshot
![photo_2018-01-28_12-52-39](https://user-images.githubusercontent.com/31108317/35479981-29dde6b8-042a-11e8-9331-b0a4a9bde30e.jpg)

**Comment by iamareebjamal** [comment]
How do you propose to fix it?

**Comment by jindalAnuj** [comment]
@iamareebjamal i was thinking that to make social links stick to bottom 
in detail we can move social link recyclerview from content_about_event.xml to fragment_about.xml 
which will result in removal of social links from scroolvew.

**Comment by iamareebjamal** [comment]
Alright, please go ahead
