### ISSUE TITLE
No featured speakers in the speakersFragment

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-droidgen#2267]
**Actual Behaviour**

In the web app, the featured speakers are displayed first and then all the speakers are displayed
But in the Android app there are no featured speakers,all the speakers are displayed at the same time

**Expected Behaviour**

Android app should have the same features of the website and have a featured speakers section before all the speakers are displayed in the speakers fragment

**Steps to reproduce it**

Open speakers fragment 

**Screenshots of the issue**

![screenshot_20180128-131605](https://user-images.githubusercontent.com/20878145/35480111-addf3e50-042d-11e8-83bb-72c16c28b367.png)

**Would you like to work on the issue?**

Yes
@iamareebjamal views?

**Comment by dr0pdb** [comment]
Duplicate #1708 
It is already been worked upon.

**Comment by nikit19** [comment]
Oh I did not see that.
