### ISSUE TITLE
Extract out the common code between FeedFragment and TwitterFeedFragment.

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2272]
**Actual Behaviour**

Currently there is a lot of common code between FeedFragment which gets the facebook feeds and the TwitterFeedFragment which gets the Twitter feeds.

**Expected Behaviour**

Those can be extracted out to a common class and hence reduce the code duplication.

**Would you like to work on the issue?**

Yes

To be done after #2263 gets merged.

**Comment by iamareebjamal** [comment]
Please make a common abstract class to do it

**Comment by dr0pdb** [comment]
@iamareebjamal 
I have a small query. I am done creating the abstract class. I also want to extract the common code from layout's also since they are almost identical. I am using ```<include>``` for it. The problem is that ```Butterknife``` can't find the views associated with the included view group.

Following are the proposed solutions:

1. Suggested by Jake Wharton: [here](https://github.com/JakeWharton/butterknife/issues/393#issuecomment-148489697)

2. A simpler implementation: [here](https://github.com/JakeWharton/butterknife/issues/393#issuecomment-300748482)

The use case is not same but it is very similar to the issue. Which option would you suggest using ?

**Comment by iamareebjamal** [comment]
Both are fine
