### ISSUE TITLE
Add FAQs section

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-droidgen#2284]
**Actual Behaviour**

There is no FAQ section in the app.

**Expected Behaviour**

There should be one.

**Would you like to work on the issue?**

Yes

@iamareebjamal Should we add this?

**Comment by iamareebjamal** [comment]
Please add proposed contents here

**Comment by mayank8318** [comment]
There are APIs for FAQs : https://open-event-api.herokuapp.com/#faq-event-faq-collection-get
![image](https://user-images.githubusercontent.com/22395998/35622722-db35dc82-06ae-11e8-80de-793c7db7d14f.png)

**Response** - 
{
  "meta": {
    "count": 1
  },
  "data": [
    {
      "relationships": {
        "faq-type": {
          "links": {
            "self": "/v1/faqs/1/relationships/faq-type",
            "related": "/v1/faqs/1/faq-type"
          }
        },
        "event": {
          "links": {
            "self": "/v1/faqs/1/relationships/event",
            "related": "/v1/faqs/1/event"
          }
        }
      },
      "attributes": {
        "question": "Sample Question",
        "answer": "Sample Answer"
      },
      "type": "faq",
      "id": 1,
      "links": {
        "self": "/v1/faqs/1"
      }
    }
  ],
  "jsonapi": {
    "version": "1.0"
  },
  "links": {
    "self": "/v1/events/1/faqs"
  }
}

So we can fetch this and store it locally. Make a new fragment for FAQs since this is important for any event app. Also we can make the FAQs searchable since the number of FAQs might be large and this is will make it easier for the user to look for what he wants.

All in all this will increase the functionality of the app and we will be making use of a relevant API feature.

**Comment by mayank8318** [comment]
Closing as there is no sample faqs presently

**Comment by iamareebjamal** [comment]
There's no need of sample FAQs, you can add your own FAQs to test
