### ISSUE TITLE
Add notifications in the application

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2289]
**Actual Behaviour**

The API supports [notifications](https://open-event-api.herokuapp.com/#notifications) but it is not implemented in the app.

**Expected Behaviour**

It should be implemented.

**Would you like to work on the issue?**

Yes

**Comment by jindalAnuj** [comment]
@srv-twry  it is good idea as there is a lot of information about notification in api
@mayank8318 @nikit19 what do you think

**Comment by dr0pdb** [comment]
Yes, i have already discussed with the mentor on this.

**Comment by jindalAnuj** [comment]
@srv-twry is there any other channel or medium where we can discuss our ideas instead of issues tracker

**Comment by dr0pdb** [comment]
Yes, there is one. You can use [gitter](https://gitter.im/fossasia/open-event-android).

PS: My discussion took place in the orga app, where i created this issue even though it was supposed to be here.

**Comment by shivaraju07** [comment]
Can you explain what would be there in the notification?
@srv-twry 
For which activities you are doing?

**Comment by shivaraju07** [comment]
Are you creating push notification?

**Comment by dr0pdb** [comment]
No, it's not a push notification. The notifications will be fetched from the API.

> Can you explain what would be there in the notification?

Please explore the API link that i have provided in this issue. I haven't explored it that much, i will do it later.

> For which activities you are doing?

Most probably inside the MainActivity but open to suggestions.

**Comment by shivaraju07** [comment]
I am thinking to create an email notification is it good?

**Comment by dr0pdb** [comment]
Create an issue for it and we can discuss it there.

**Comment by dr0pdb** [comment]
@iamareebjamal How would you suggest implementing this ? 
I think we could add an notification icon on the action bar in the AboutFragment which would take the user to a fragment containing the recycler view with all the notifications.

**Comment by iamareebjamal** [comment]
It should be a separate menu in navigation drawer IMO

**Comment by dr0pdb** [comment]
Yeah, i will add that, but it's a standard to show atleast the notification icon with the count of notifications on the main screen.

**Comment by iamareebjamal** [comment]
AboutFragment is doing too much of a task IMO, so we'll see later what can be done but I'll recommend not to bloat an already bloated view

**Comment by dr0pdb** [comment]
@iamareebjamal Should i cache the notifications in the db or just treat it like a LiveFeed ?

**Comment by iamareebjamal** [comment]
Add it in db
