### ISSUE TITLE
Adding Feedback Response from User

### ISSUE THREAD

**Issue by shivaraju07** [fossasia/open-event-droidgen#2293]
**Actual Behaviour**

API provides Feedback but it is not utilized in application

**Expected Behaviour**

In the home menu of items selected drop-down adding a feedback response button from the user and the response is sent to the Admin Email.

**Screenshots of the issue**

![media-20180131](https://user-images.githubusercontent.com/18509469/35638931-806042fe-06de-11e8-80e3-2b3cc648be01.jpg)
adding down to download latest data .

after selecting the feedback response button a new activity opens in which user has to give the feedback/suggestions and there is a send button to send it.

**Would you like to work on the issue?**

yes

any Views?

**Comment by simarsingh24** [comment]
@shivaraju07 does this issue include viewing feedbacks related to event?

**Comment by shivaraju07** [comment]
NO,
it is like a form in which you have to enter the feedback/opinions on the app and sends to the admin.
OR
it can be feedback/rating on an event.
Which one is nice so that I can start working on it?

any suggestions?
@simarsingh24

**Comment by simarsingh24** [comment]
@iamareebjamal should feedback be open like comment so that the users could see them because here they are like review of an event
<img width="727" alt="screen shot 2018-02-01 at 12 17 09 am" src="https://user-images.githubusercontent.com/16715499/35641135-556de1e4-06e5-11e8-876b-19c6126bec21.png">
In this case for example "Awesome Event"

**Comment by shivaraju07** [comment]
yeah! I saw this one but I don't know which one is better either to display or not.
@simarsingh24

**Comment by simarsingh24** [comment]
let's wait for the mentor for his views!

**Comment by iamareebjamal** [comment]
@shivaraju07 @simarsingh24 There were several old issues regarding this feature, let's reopen one of those and discuss there, please mention me in one of the more relevant old issues
