### ISSUE TITLE
Adding feedback functionality under an user

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-droidgen#2299]
**Expected Behaviour**
The feedback posting functionality is present in the API [feedback](https://open-event-api.herokuapp.com/#feedback). It would be nice to implement it in the app.

**Would you like to work on the issue?**
 Yes
@iamareebjamal @simarsingh24 your views on this?

**Comment by iamareebjamal** [comment]
Duplicate of #2293
