### ISSUE TITLE
Removal of all the unused methods and preventing memory leak

### ISSUE THREAD

**Issue by gakarod** [fossasia/open-event-droidgen#2305]
**Actual Behaviour**

While analysing the source code , there are a large number of unused methods which hamper 
the readability of the functions. Many functions are idles and are just consuming unnecessary memory.

**Expected Behaviour**

The source code should be free of memory leak and as readable as possible for the open source community to work on it.

**Would you like to work on the issue?**

Yes.

**Comment by dr0pdb** [comment]
@gakarod Can you name a few instances where there are unused methods ?

> Many functions are idles and are just consuming unnecessary memory.

Why would they consume memory ? 

> The source code should be free of memory leak

Again, please add a couple of instances where you found the memory leak.

**Comment by gakarod** [comment]
Sir

In multiple classes of the UI folder , many functions are not used and are
hampering the readability of the code

Thank you

On 02-Feb-2018 5:30 PM, "Saurav Tiwary" <notifications@github.com> wrote:

@gakarod <https://github.com/gakarod> Can you name a few instances where
there are unused methods ?

Many functions are idles and are just consuming unnecessary memory.

Why would they consume memory ?

The source code should be free of memory leak

Again, please add a couple of instances where you found the memory leak.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fossasia/open-event-android/issues/2305#issuecomment-362568188>,
or mute the thread

**Comment by dr0pdb** [comment]
> n multiple classes of the UI folder , many functions are not used and are
hampering the readability of the code

I understood the problem but what i asked for is some names, so that i could verify it. ```ui``` folder is itself so big. I wanted some specific class names. 
Anyways i checked all of them manually and yeah, ```StickyRecyclerHeadersDecoration``` has an unused constructor and ```StickyRecyclerHeadersTouchListener``` is a completely unused class.

You haven't mentioned anything about the memory leak. Where is the memory leak ?

Also, please don't call me sir :smile:

**Comment by gakarod** [comment]
There is not something as particular that I can call a memory leak but
some of the unused classes require getters on initial project setup which
just seemed odd to me as the functions are not used anymore and
unnecessarily we have to maintain them

Please pardon me if I was wrong about the issue due to my limited knowledge

Thanks

**Comment by iamareebjamal** [comment]
I think there is some misunderstanding (about lombok plugin) on your side @gakarod 

@srv-twry and I myself would just like to know about which unused methods are you talking about. We'll surely want to remove unused code and things which are causing memory leaks but without knowing which code and methods you are talking about, it is difficult to know if we are on the same page and talking about the same thing

**Comment by gakarod** [comment]
Sorry for inconvenience,

In the dialogfactory class of UI folder , there are 4-5 unused methods ,
similarly in other classes of the UI folder there where unused segment of
code is present.

I am not sure , if those methods are kept there for some future reference
but it just seemed odd to me.

If there was a mistake from my side in interpreting the code please pardon
me.

**Comment by simarsingh24** [comment]
@gakarod that's what @iamareebjamal and @srv-twry are asking, can you name some of the unused functions?

**Comment by gakarod** [comment]
Dialogfactory class has a bunch of methods which are not used anymore
please check it

On 04-Feb-2018 7:14 PM, "Harsimar" <notifications@github.com> wrote:

@gakarod <https://github.com/gakarod> that's what @iamareebjamal
<https://github.com/iamareebjamal> and @srv-twry
<https://github.com/srv-twry> are asking, can you name some of the unused
functions?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fossasia/open-event-android/issues/2305#issuecomment-362907861>,
or mute the thread

**Comment by gakarod** [comment]
can i resolve this issue ?

**Comment by dr0pdb** [comment]
> Dialogfactory class has a bunch of methods which are not used anymore
please check it

As it has been stated before, can you just name a few of those methods? The reason we are asking you to name them is not because we are lazy and don't want to check them on our own. It's because in my opinion there are no unused methods. Now since you're saying that there are some, then please name them. 
Not only the **Class** , but both Class and it's unused **methods**.

**Comment by gakarod** [comment]
Apologies Sir

I am still new to this so I didn't know the how much of data I need to give
.

As for the unused methods there were 4 methods namely -

createprogressdialogue, creategenericerrordialog,
Createaimpleactiondialogue,
Createsimpleokerrordialogue

In dialogfactory class located in java/org.fossasia.openevent/common/ui

I also found some others in other classes in ui folder

Please pardon me for bad communication from my side , i hope this will be
enough.

**Comment by dr0pdb** [comment]
@iamareebjamal I think we can close this due to inactivity.
