### ISSUE TITLE
Correct spacing and indentation in the whole project

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-droidgen#2316]
**Actual Behaviour**
Some part of the code in the whole project is missing correct spacing and indentation.

**Expected Behaviour**
This should not be the case

**Would you like to work on the issue?**
Yes

**Comment by dreadpool2** [comment]
@iamareebjamal Can I work on this?

**Comment by dr0pdb** [comment]
@dreadpool2 Can you name a few instances where this is happening ?

**Comment by dreadpool2** [comment]
@srv-twry By completely searching the project I found out instances where no space in if statements and for loops where there.
For eg - `if(`   and `for(`
Even in files like WidgetUpdater.java `,widgetIds` type formatting is present.
Like no spaces after commas

**Comment by dr0pdb** [comment]
Ok, IMO this is not a major issue and definitely not a priority right now. If you want you can definitely send the PR but i would suggest you focus on the core features of the app and try and understand them more, specially #2288 . It will really help you get familiar with everything the project is about i.e. the android app, the app generator and the api itself.

**Comment by dr0pdb** [comment]
@dreadpool2 Please close this also. Once we have a large number of these issues, we can open it.
