### ISSUE TITLE
In About Fragment Sessions are being displayed after bookmark is removed

### ISSUE THREAD

**Issue by shivaraju07** [fossasia/open-event-droidgen#2319]
**Actual Behaviour**

In About Fragment Sessions are being displayed after bookmark is removed.

**Expected Behaviour**

It should be removed from the About fragment.

**Screenshots of the issue**

![gif-180205_220823](https://user-images.githubusercontent.com/18509469/35817532-ada3c716-0ac3-11e8-842a-b6e03c367b33.gif)

**Would you like to work on the issue?**

Yes

@iamareebjamal  Should I Start Working on this ?

**Comment by simarsingh24** [comment]
@shivaraju07 did you mean bookmarked session?

**Comment by shivaraju07** [comment]
Yes! As You can see in the GIF.

**Comment by simarsingh24** [comment]
@shivaraju07 what is the status of this issue?

**Comment by shivaraju07** [comment]
the issue is resolved in this PR.
#2329
