### ISSUE TITLE
Fix travis ci build

### ISSUE THREAD

**Issue by dr0pdb** [fossasia/open-event-droidgen#2322]
**Actual Behaviour**

Currently the Travis CI build fails.
This issue has been registered before for version 27.0.2 and i think it should be the same problem as this one. 
1. [First](https://github.com/travis-ci/travis-ci/issues/8874)
2. [Second](https://github.com/travis-ci/travis-ci/issues/8651)

**Expected Behaviour**

It should build properly.

**Steps to reproduce it**

Open a PR.

**LogCat for the issue**
```

FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 27.0.3].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
```

**Would you like to work on the issue?**

Yes.

@iamareebjamal Please review the above links and also the build logs of my PR #2320 in order to confirm that it is the same issue.

**Comment by iamareebjamal** [comment]
Yes, it is the same issue. We'll have to update `.travis.yml`
