### ISSUE TITLE
Move both Twitter and Facebook feed under one fragment

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-droidgen#2326]
**Actual Behaviour**

Currently, there are two separate items in the drawer for twitter and facebook.

**Expected Behaviour**

I propose to move both the fragments under a common "Live Feed" fragment using a `View Pager`.

**Would you like to work on the issue?**

Yes

@iamareebjamal @srv-twry Please see if this is a good change and is it required atm?

**Comment by iamareebjamal** [comment]
Yes it is required
