### ISSUE TITLE
Speakers' color changes in SpeakerListFragment when search is being done

### ISSUE THREAD

**Issue by leeyh20** [fossasia/open-event-droidgen#2348]
**Actual Behaviour**
Speakers' color changes in SpeakerListFragment when search is being done

**Expected Behaviour**
Speakers' color should not change in SpeakerListFragment when search is being done

**Screenshots of the issue**
![bugatspeakers](https://user-images.githubusercontent.com/7023320/36351732-256f4e44-14e9-11e8-92de-b23947183d82.gif)

See the speaker on the top right. His panel changes from red to blue.
It sometimes changes to yelllow too.

**Would you like to work on the issue?**
Yes, though I'm not sure where the colors of the speakers are set.
Has this issue been reported before?

**Comment by iamareebjamal** [comment]
It is set in the Speaker ViewHolder as far as I know. It may be a bug in Android Color Palette

**Comment by leeyh20** [comment]
Thanks for pointing out where it is set!
It is caused by some of the images not having a "vibrant" swatch profile, thus not setting its background color explicitly causes the change in color. 

I have made a PR to solve this.
