### ISSUE TITLE
Crash: App crashes if default calendar app is disabled

### ISSUE THREAD

**Issue by 97balakrishnan** [fossasia/open-event-droidgen#2349]
**Actual Behaviour**

![screenshot_20180218-180318](https://user-images.githubusercontent.com/20266120/36351940-dd8f1990-14d6-11e8-89c5-27ba735b3ddf.png)

**Expected Behaviour**

Display a toast that calendar app is unavailable

**Would you like to work on the issue?**

Yes

**Comment by anipmehta** [comment]
@97balakrishnan Are you still working on this issue?

**Comment by 97balakrishnan** [comment]
Yes

**Comment by sriramr98** [comment]
@97balakrishnan any updates?

**Comment by iamareebjamal** [comment]
@sriramr98 Take it up please
