### ISSUE TITLE
Error in signing up

### ISSUE THREAD

**Issue by rideep** [fossasia/open-event-droidgen#2354]
Actual Behaviour
![screenshot_2018-02-28-01-14-47](https://user-images.githubusercontent.com/17199525/36751211-827bf914-1c25-11e8-890c-3b2639a739fe.png)

Expected Behaviour

Log the user in straight away after a successful signup

Would you like to work on the issue?

Yes

**Comment by the-dagger** [comment]
@rideep What's the progress on the issue?
Let me know if you need help, @sriramr98 was willing to work on the issue as well, so maybe you two can work together.

**Comment by iamareebjamal** [comment]
Please look at this issue https://github.com/fossasia/open-event-orga-app/issues/680

**Comment by rideep** [comment]
@the-dagger I am working on the issue.In SignupActivity getResponse() is highlighted as 'cant resolve method'.And instead of using switch can use if-else.

**Comment by iamareebjamal** [comment]
@rideep The solution (as mentioned in the issue I linked above) is simply to change the base URL in the config.json. There is no need to change any code at all
