### ISSUE TITLE
opening the event and removing the bookmark doesn't update the AboutFragment.java

### ISSUE THREAD

**Issue by raj10071997** [fossasia/open-event-droidgen#2356]
**Actual Behaviour**

On opening an event in the bookmark recycler view of AboutFragment.java and removing the bookmark doesn't remove the event from the list. Instead only the bookmark sign is removed.

**Expected Behaviour**

The event should be removed from the list.

**Gif of the issue**

![videotogif_2018 03 07_19 49 13](https://user-images.githubusercontent.com/24502136/37097499-9f09ed3a-2241-11e8-9a72-8c9586bc82af.gif)

**Would you like to work on the issue?**

Yes.

**Comment by sriramr98** [comment]
Is someone working on this issue? I have the fix and I would like to send a PR.

**Comment by iamareebjamal** [comment]
Adding the listener in onResume is a hack and not a fix. Do you have any other fix? :smile:

**Comment by sriramr98** [comment]
I haven't yet sent a PR for this issue. You've commented on the wrong issue.

**Comment by iamareebjamal** [comment]
Just discussing your approach to the solution

**Comment by ParthivMangukiya** [comment]
@iamareebjamal Apologies, I hadn't known this issue was open. This has been fixed by #2383.
