### ISSUE TITLE
ic_launcher icon does not render in navigation header

### ISSUE THREAD

**Issue by ParthivMangukiya** [fossasia/open-event-droidgen#2361]
**Actual Behaviour**

ic_launcher icon does not render in navigation header in apk generated by apk generator.

**Expected Behaviour**

ic_launcher icon should render in navigation header.

**Steps to reproduce it**

1. Generate apk from samples provided in https://github.com/fossasia/open-event/tree/master/sample through apk generator.
2. Open navigation drawer.

**Screenshots of the issue**

![20180310_151547](https://user-images.githubusercontent.com/19627767/37240780-12b228a2-2476-11e8-973b-e465c0ac7bc5.gif)

**Would you like to work on the issue?**

yes

**Comment by ParthivMangukiya** [comment]
This is happening because ic_launcher image is too big to render.
Apk generator directly resize file by asuming that **logo.png** provided in sample is **ldpi** size and with reference to it generates  mdpi,hdpi format.
Whether should I make change in **apk generator** to resize logo image to size required for app **OR** should I make change in **app** to resize the image generated by apk generator?

**Comment by iamareebjamal** [comment]
The generator should already be resizing the images, it not, please fix the generator

**Comment by ParthivMangukiya** [comment]
@iamareebjamal I found that logo_url used in googleio17 sample is /images/io_logo.png and it is not able to download image using that url so image does not render. I added on error resource id in setNavHeader function and made PR. Please Review.

**Comment by iamareebjamal** [comment]
Then it is not the issue with the app, rather with the sample

**Comment by ParthivMangukiya** [comment]
@iamareebjamal I think even if this is issue of sample, It is good to set placeholder image rather than showing blank instead(There may happen any kind of error during downloading image from url).

**Comment by iamareebjamal** [comment]
Agreed
