### ISSUE TITLE
app downloads data on cellular even though download only over wifi is turned on

### ISSUE THREAD

**Issue by vivek1339** [fossasia/open-event-droidgen#2364]
downloading new feeds is the same even when download only over wifi is enabled 
it is giving a prompt that charges may apply in both the cases(download only over wifi is turned on or off)
Would you like to work on the issue?
yes

**Comment by mayank8318** [comment]
@vivek1339 Please follow the issue template :)

**Comment by mayank8318** [comment]
@vivek1339 Are you working on this?

**Comment by swaroop-nath** [comment]
If anyone's not working on it, I would like to take up the issue.

**Comment by sriramr98** [comment]
@swaroop-nath Do you have the fix yet?

**Comment by vivek1339** [comment]
Yes I would like to work on this I was waiting because I did not get a proper acceptance on the issue

**Comment by sriramr98** [comment]
@vivek1339 You can start working on this. This is a critical bug that needs to be fixed.

**Comment by sriramr98** [comment]
@vivek1339 You can start working on this. This is a critical bug that needs to be fixed.

**Comment by sriramr98** [comment]
@vivek1339 any updates? Are you still working on this?

**Comment by vivek1339** [comment]
actually i am working and had to halt for applying to gsoc just give me a week and i'll get back with a proper solution 
thanks,
vivek

**Comment by sriramr98** [comment]
@iamareebjamal Can I take this up? There hasn't been a PR yet.

**Comment by iamareebjamal** [comment]
Go ahead
