### ISSUE TITLE
Update library dependencies in the application.

### ISSUE THREAD

**Issue by sriramr98** [fossasia/open-event-droidgen#2366]
**Steps to reproduce it**

There are many library dependencies for the application that needs to be updated to newer and latest versions. This gives us the latest and more stable code from the libraries and thus makes the application more stable. 

**Would you like to work on the issue?**
Yes

**Target Milestone to solve the issue**
It can be solved in a small fix.

**Comment by sriramr98** [comment]
@iamareebjamal What do you think?

**Comment by iamareebjamal** [comment]
Go ahead
