### ISSUE TITLE
Add appropriate message in notifications fragment when not logged in

### ISSUE THREAD

**Issue by ParthivMangukiya** [fossasia/open-event-droidgen#2369]
**Actual Behaviour**

Empty view shows "No Notifications" in notification fragment when not logged in.

**Expected Behaviour**

Empty view should show appropriate message in notification fragment when not logged in.

**Screenshots of the issue**

![20180311_215759](https://user-images.githubusercontent.com/19627767/37256728-bab922ee-2584-11e8-9375-f3c0fcf3d6b5.gif)

**Would you like to work on the issue?**

yes

**Comment by iamareebjamal** [comment]
Showing custom message when you are directly navigated out seems like an overkill

**Comment by ParthivMangukiya** [comment]
@iamareebjamal I think that navigation flow of opening notification fragment is something odd.
If user do not want to login then he have to do two click, one to exit login activity and one for going elsewhere. 
In my point of view the good flow would be If user click notification in drawer, than he find out he should login to see notification message. There should be Login button at the bottom if he want to login.
 
But to add login button is out of this issue, so I only updated empty view message.

Please give suggestion, If this flow good than I will create new issue to change navigation flow.

**Comment by iamareebjamal** [comment]
Yes, please address this issue in a separate PR and also do it for any other fragment which needs the user to be logged in
