### ISSUE TITLE
Enhancing the LoginActivity and SignupActivity UI

### ISSUE THREAD

**Issue by akhil117** [fossasia/open-event-droidgen#2374]
**Actual Behaviour**

Lot of unused space is there and the UI can be improved by the implementation of card view.

**Expected Behaviour**

CardView can be implemented to enhance the UI. 

**Steps to reproduce it**

Navigate to the LoginActivity and SignUp Activity through the Navigation Drawer.

**Would you like to work on the issue?**

YES

**Comment by dreadpool2** [comment]
@iamareebjamal I tried to enhance it like this (Login Activity)
![2018_05_19_13 12 06](https://user-images.githubusercontent.com/28607714/40266602-200f1d02-5b6c-11e8-9f44-a8875c9160b1.png)

**Comment by dreadpool2** [comment]
@iamareebjamal is it ok?
