### ISSUE TITLE
Convert registry classes with generated getters and setters

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-droidgen#2379]
**Actual Behaviour**

Currently, the classes generated after removing lombok are in Java and hence contain generated getters and setters 

Reference #2373

**Expected Behaviour**

Convert these classes to Kotlin

Parent Issue: #2357

**Comment by sriramr98** [comment]
I will work on this as my next step

**Comment by sriramr98** [comment]
@iamareebjamal I guess this issue can be closed as I see that the StrategyRegistry class and other Strategy classes have already been converted by you to Kotlin in the last commit from exporting Lombok dependent classes to a separate module.
