### ISSUE TITLE
Unexpected behavior : app crashes when change the language

### ISSUE THREAD

**Issue by nohadrweesh** [fossasia/open-event-droidgen#2384]
**Actual Behaviour**

App crashes when change the language to anything rather than English , when closing the app and reopen it works but it crashes again when opening settings activity.

**Expected Behaviour**

App should work without crashing after changing language .

**Screenshots of the issue**

![open_event_android](https://user-images.githubusercontent.com/20757813/37654335-6574a1ba-2c4a-11e8-9b72-3f310701a6ec.gif)

**Would you like to work on the issue?**

yes.

**Comment by iamareebjamal** [comment]
I think that this setting should be removed from settings as this is not the responsibility of the app

**Comment by sriramr98** [comment]
Can I take this up?

**Comment by iamareebjamal** [comment]
Please outline what you'll do

**Comment by sriramr98** [comment]
@iamareebjamal  As you suggested, we can remove the setting from the settings screen. Later on, we can add translations and show a list of supported languages instead of using system's default language.

**Comment by iamareebjamal** [comment]
Translations are already there but incomplete. And the functionality to show supported language is not concern of the app as Android handles it already

**Comment by sriramr98** [comment]
So the setting can be removed from the settings screen?

**Comment by iamareebjamal** [comment]
Yes, but test if it crashes after changing languages still
