### ISSUE TITLE
UI Accent Color not good

### ISSUE THREAD

**Issue by DipanshKhandelwal** [fossasia/open-event-droidgen#2385]
**Actual Behaviour**
Present accent color looks too away from the theme of the app.

![helloold](https://user-images.githubusercontent.com/24923974/37696037-98e59f18-2cf9-11e8-8616-2ea11b324af0.png)

**Expected Behaviour**

I got a color which looks good with the present UI.
![hello](https://user-images.githubusercontent.com/24923974/37696033-9134fcf0-2cf9-11e8-9046-ee89fe81f9aa.png)

**Would you like to work on the issue?**
Yes, I would like to work on it,

**Comment by mani87** [comment]
Can i work on this issue?

**Comment by iamareebjamal** [comment]
This is automatically set using the app generator to whatever color you want, so there's no issue
