### ISSUE TITLE
Let the user choose his sharing medium everytime

### ISSUE THREAD

**Issue by mayank8318** [fossasia/open-event-droidgen#2395]
**Actual Behaviour**

Presently, a default sharing medium is selected(according to the user's preference).

**Expected Behaviour**

We should let the user choose the sharing medium everytime he wants to share anything.
This involves using `Intent.createChooser()`

**Steps to reproduce it**

Share anything from the app.
Now try to share again

**Would you like to work on the issue?**

Yes

**Comment by sriramr98** [comment]
Can you send a screenshot? In which Activity/Fragment are you facing this problem

**Comment by mayank8318** [comment]
This happens when you choose `share` from the drawer. Also, try sharing a speaker. The implementation is different. I will use this implementation for sharing an event.

**Comment by sriramr98** [comment]
I tried them. Every time I got options to share through different applications. Make sure you pull the changes from the development branch and try again.

**Comment by mayank8318** [comment]
Yes I did

**Comment by mayank8318** [comment]
Share again

**Comment by sriramr98** [comment]
I did. Can you send some screen shots?

**Comment by mayank8318** [comment]
Speaker Details :
![screenshot from 2018-03-25 22-46-34](https://user-images.githubusercontent.com/22395998/37877873-709eec7a-307e-11e8-95f3-295c144595ec.png)

Share application :
![screenshot from 2018-03-25 22-46-49](https://user-images.githubusercontent.com/22395998/37877875-7768035c-307e-11e8-9457-2e9b7721ad35.png)

As you can see, the two implementations are different and hence the execution. Sorry, I am having issues with my phone so cannot provide a GIF as of now but I hope this helps :)

**Comment by sriramr98** [comment]
@iamareebjamal  What do you think?

**Comment by iamareebjamal** [comment]
I don't get what the issue is

**Comment by mayank8318** [comment]
@iamareebjamal If the user shares the app once then whichever medium he uses for sharing(be it WhatsApp, Messenger etc) that is set as the default choice by the system. But if we use `Intent.createChooser()` as is done in sharing a speaker's details, the user will get to choose his medium of sharing every time

**Comment by mayank8318** [comment]
These are two different ways of doing it and in my opinion the second method is more user friendly and is used by almost all the apps these days

**Comment by iamareebjamal** [comment]
OK. go ahead
