### ISSUE TITLE
App crashes on click of the track "OpenTech"

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-droidgen#2435]
**Actual Behaviour**

The app crashes on click of the track "OpenTech"

**Expected Behaviour**

This should not happen

**Would you like to work on the issue?**

Yes

**Comment by nikit19** [comment]
Pull the latest changes. This shouldn't happen

**Comment by dreadpool2** [comment]
Okay!

**Comment by dreadpool2** [comment]
@nikit19 Yup working 👍
