### ISSUE TITLE
Login Button and textview visible in all fragments 

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-droidgen#2454]
**Actual Behaviour**

If you open the FAQ fragment and then go to some other fragment say discount codes fragment.
The login button and "Please login to continue" text is visible everywhere

**Expected Behaviour**

It should not be visible after we leave the FAQ fragment

**Steps to reproduce it**

Open the app.
Go to FAQ fragment.
Go to Discount Codes fragment and click the back button

**Screenshots of the issue**

![screenshot_20180514-153951](https://user-images.githubusercontent.com/20878145/39991558-9ac09842-578d-11e8-98b7-7da6483f1cf1.png)
![screenshot_20180514-153750](https://user-images.githubusercontent.com/20878145/39991561-9c03f0e6-578d-11e8-9cf6-5017b77b2214.png)

**Would you like to work on the issue?**

Yes

**Comment by SAITARUN55** [comment]
Yes I'm interested in working on this issue

**Comment by SAITARUN55** [comment]
Yes I'm interested in working on this issue

**Comment by nikit19** [comment]
@SAITARUN55 actually I have finished working on it. You can create a new issue for any bugs that you find in the app :)
