### ISSUE TITLE
feat add : redirect to fragment specific to Text View of tracks

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-droidgen#2472]
**Expected Behaviour**

Attaching click listeners to the text views (inside card view) of tracks and redirecting to the corresponding fragment.
Ex- When Denis Nek will be clicked it would take the user to the speaker info fragment of Denis Nek
similarly selecting Dalton Hall will take user to all the sessions happening at Dalton hall

**Screenshots of the issue**

![screenshot_20180517-105538](https://user-images.githubusercontent.com/16715499/40158256-0eefe7e2-59c1-11e8-9643-1a534404daa5.png)

**Would you like to work on the issue?**

Yes

**Comment by simarsingh24** [comment]
@iamareebjamal what are your view on this?

**Comment by iamareebjamal** [comment]
Go ahead
