### ISSUE TITLE
feat : Having a single activity in which compiled event statistics is shown

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-droidgen#2475]
**Expected Behaviour**

We can have a single activity where all event statistics can be compiled and shown to the user.
We do have the API endpoint
![screenshot from 2018-05-17 22-50-34](https://user-images.githubusercontent.com/28607714/40194240-54d11478-5a27-11e8-875c-6af5868a2759.png)

**Would you like to work on the issue?**

Yes

**Comment by dreadpool2** [comment]
@iamareebjamal What are your views on this ?

**Comment by iamareebjamal** [comment]
This is not for users, it's for organizers
