### ISSUE TITLE
feat : Added a gradient colour to the nav_header

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-droidgen#2476]
**Actual Behaviour**

The colour present was a solid one and the logo didn't look good in the background

**Expected Behaviour**

Added a gradient colour with start and end colours as the colour_primary_dark and the center colour as white so that much emphasis is created on the logo

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

![2018_05_18_10 43 51](https://user-images.githubusercontent.com/28607714/40217121-b1fb628c-5a88-11e8-9b15-1d942865db0f.png)

**Would you like to work on the issue?**

Yes
@iamareebjamal Does it look good or should I revert back ?

**Comment by iamareebjamal** [comment]
No, this will be covered by feature image
