### ISSUE TITLE
Change the tab headers of the Feed fragment by icons

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-droidgen#2479]
**Actual Behaviour**

The labels FACEBOOK and TWITTER are provided as tab headers

**Expected Behaviour**

Icons should be present for better UI

**Would you like to work on the issue?**

Yes

**Comment by dreadpool2** [comment]
@iamareebjamal The feed window looks like this
![2018_05_18_16 36 43](https://user-images.githubusercontent.com/28607714/40231744-df170736-5ab9-11e8-8408-76eed0f3b15a.png)

**Comment by iamareebjamal** [comment]
Doesn't look good

**Comment by dreadpool2** [comment]
Should I change the icon set with matching colours or use the text headers only ?

**Comment by iamareebjamal** [comment]
Text only is fiine
